"""ordem de missão

Revision ID: 029a74e6f1b3
Revises: 8e45a036c6f5
Create Date: 2026-01-11 10:51:56.662097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '029a74e6f1b3'
down_revision: Union[str, None] = '8e45a036c6f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('om_etiquetas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cor', sa.String(length=7), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('om_ordens_missao',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('matricula_anv', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('projeto', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('campos_especiais', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('uae', sa.String(length=20), nullable=False),
    sa.Column('esf_aer', sa.Integer(), nullable=False),
    sa.Column('doc_ref', sa.String(length=100), nullable=True),
    sa.Column('data_saida', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('om_etapas',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('ordem_id', sa.Integer(), nullable=False),
    sa.Column('dt_dep', sa.DateTime(timezone=True), nullable=False),
    sa.Column('origem', sa.String(length=10), nullable=False),
    sa.Column('dest', sa.String(length=10), nullable=False),
    sa.Column('dt_arr', sa.DateTime(timezone=True), nullable=False),
    sa.Column('alternativa', sa.String(length=10), nullable=False),
    sa.Column('tvoo_etp', sa.Integer(), nullable=False),
    sa.Column('tvoo_alt', sa.Integer(), nullable=False),
    sa.Column('qtd_comb', sa.Integer(), nullable=False),
    sa.Column('esf_aer', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['ordem_id'], ['om_ordens_missao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('om_etiqueta',
    sa.Column('ordem_id', sa.Integer(), nullable=False),
    sa.Column('etiqueta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['etiqueta_id'], ['om_etiquetas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ordem_id'], ['om_ordens_missao.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ordem_id', 'etiqueta_id')
    )
    op.create_table('om_tripulacao',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('ordem_id', sa.Integer(), nullable=False),
    sa.Column('tripulante_id', sa.Integer(), nullable=False),
    sa.Column('funcao', sa.String(length=10), nullable=False),
    sa.Column('p_g', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['ordem_id'], ['om_ordens_missao.id'], ),
    sa.ForeignKeyConstraint(['p_g'], ['posto_grad.short'], ),
    sa.ForeignKeyConstraint(['tripulante_id'], ['tripulantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('om_tripulacao')
    op.drop_table('om_etiqueta')
    op.drop_table('om_etapas')
    op.drop_table('om_ordens_missao')
    op.drop_table('om_etiquetas')
    # ### end Alembic commands ###
