"""pernoites rev

Revision ID: 09a44a4f187b
Revises: c7890207b58e
Create Date: 2025-10-22 11:26:19.504545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '09a44a4f187b'
down_revision: Union[str, None] = 'c7890207b58e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('frag_mis', sa.Column('acrec_desloc', sa.Boolean(), server_default='false', nullable=False), schema='cegep')
    op.alter_column('pernoite_frag', 'data_ini',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               nullable=False,
               schema='cegep')
    op.alter_column('pernoite_frag', 'data_fim',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               nullable=False,
               schema='cegep')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pernoite_frag', 'data_fim',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               schema='cegep')
    op.alter_column('pernoite_frag', 'data_ini',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               schema='cegep')
    op.drop_column('frag_mis', 'acrec_desloc', schema='cegep')
    # ### end Alembic commands ###
