"""cadastro de subprogramas e estrutura do paop

Revision ID: 0ac6c65c50dc
Revises: a826ee3bcd9e
Create Date: 2026-08-20 07:19:25.004137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ac6c65c50dc'
down_revision: Union[str, None] = 'a826ee3bcd9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paops',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('uae', sa.String(length=20), nullable=False),
    sa.Column('ano', sa.SmallInteger(), nullable=False),
    sa.Column('data_ini', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.ForeignKeyConstraint(['uae'], ['tenants.organizacao_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uae', 'ano', name='uq_paops_uae_ano'),
    schema='instrucao'
    )
    op.create_table('subprogramas',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('uae', sa.String(length=20), nullable=False),
    sa.Column('codigo', sa.String(length=7), nullable=False),
    sa.Column('descricao', sa.String(length=120), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('func', sa.String(length=3), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['func'], ['funcoes.cod'], name='fk_subprogramas_func', onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['uae'], ['tenants.organizacao_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uae', 'codigo', name='uq_subprogramas_uae_codigo'),
    schema='instrucao'
    )
    op.create_table('paop_subprogramas',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('paop_id', sa.Integer(), nullable=False),
    sa.Column('subprograma_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['paop_id'], ['instrucao.paops.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subprograma_id'], ['instrucao.subprogramas.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paop_id', 'subprograma_id', name='uq_paop_subprogramas'),
    schema='instrucao'
    )
    op.create_table('tripulante_subprogramas',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('paop_subprograma_id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('data_inclusao', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['paop_subprograma_id'], ['instrucao.paop_subprogramas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['tripulantes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paop_subprograma_id', 'trip_id', name='uq_tripulante_subprogramas'),
    schema='instrucao'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tripulante_subprogramas', schema='instrucao')
    op.drop_table('paop_subprogramas', schema='instrucao')
    op.drop_table('subprogramas', schema='instrucao')
    op.drop_table('paops', schema='instrucao')
    # ### end Alembic commands ###
