"""initial schema

Revision ID: 0c4c4b16398e
Revises: 
Create Date: 2026-06-07 16:29:58.214604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c4c4b16398e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # squash: schemas derivados automaticamente
    for _schema in (
        'aeromedica',
        'cegep',
        'estatistica',
        'instrucao',
        'inteligencia',
        'nav',
        'security',
        'seg_voo',
    ):
        op.execute(f'CREATE SCHEMA IF NOT EXISTS {_schema}')
    op.create_table('aeronaves',
    sa.Column('matricula', sa.String(length=4), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('sit', sa.String(length=2), nullable=False),
    sa.Column('obs', sa.String(), nullable=True),
    sa.Column('is_sim', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('matricula')
    )
    op.create_table('etiqueta',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cor', sa.String(length=7), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='cegep'
    )
    op.create_table('frag_mis',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('tipo_doc', sa.String(), nullable=False),
    sa.Column('n_doc', sa.Integer(), nullable=False),
    sa.Column('desc', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('afast', sa.DateTime(), nullable=False),
    sa.Column('regres', sa.DateTime(), nullable=False),
    sa.Column('acrec_desloc', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('obs', sa.String(), nullable=True),
    sa.Column('indenizavel', sa.Boolean(), nullable=False),
    sa.Column('custos', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='cegep'
    )
    op.create_table('orcamento_anual',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('ano_ref', sa.Integer(), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('abertura', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('fechamento', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.CheckConstraint('abertura + fechamento = total', name='ck_orcamento_anual_soma_cotas'),
    sa.CheckConstraint('abertura >= 0', name='ck_orcamento_anual_abertura_pos'),
    sa.CheckConstraint('fechamento >= 0', name='ck_orcamento_anual_fechamento_pos'),
    sa.CheckConstraint('total >= 0', name='ck_orcamento_anual_total_pos'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ano_ref', name='uq_orcamento_anual_ano_ref'),
    schema='cegep'
    )
    op.create_table('valor_diarias',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('grupo_pg', sa.Integer(), nullable=False),
    sa.Column('grupo_cid', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='cegep'
    )
    op.create_table('estados',
    sa.Column('codigo_uf', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('uf', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uf')
    )
    op.create_table('esf_aer',
    sa.Column('id', sa.SmallInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('modelo', sa.String(), nullable=False),
    sa.Column('grupo', sa.String(), nullable=False),
    sa.Column('prog', sa.String(), nullable=False),
    sa.Column('sub_prog', sa.String(), nullable=True),
    sa.Column('aplicacao', sa.String(), nullable=True),
    sa.Column('descricao', sa.String(), sa.Computed("grupo || ' ' || prog || COALESCE(' ' || sub_prog, '') || COALESCE(' ' || aplicacao, '')", persisted=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='estatistica'
    )
    op.create_table('missao',
    sa.Column('id', sa.SmallInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('titulo', sa.String(), nullable=True),
    sa.Column('obs', sa.String(), nullable=True),
    sa.Column('is_simulador', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='estatistica'
    )
    op.create_table('tipo_missao',
    sa.Column('id', sa.SmallInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('cod', sa.String(length=4), nullable=False),
    sa.Column('desc', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='estatistica'
    )
    op.create_table('om_etiquetas',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cor', sa.String(length=7), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizacoes',
    sa.Column('sigla', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('sigla_2', sa.String(length=20), nullable=True),
    sa.Column('sigla_3', sa.String(length=20), nullable=True),
    sa.Column('alias', sa.String(length=100), nullable=True),
    sa.Column('brasao_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('sigla'),
    sa.UniqueConstraint('sigla_2'),
    sa.UniqueConstraint('sigla_3')
    )
    op.create_table('posto_grad',
    sa.Column('ant', sa.Integer(), nullable=False),
    sa.Column('short', sa.String(length=2), nullable=False),
    sa.Column('mid', sa.String(), nullable=False),
    sa.Column('long', sa.String(), nullable=False),
    sa.Column('circulo', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('short')
    )
    op.create_table('oauth2_clients',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('client_id', sa.String(length=100), nullable=False),
    sa.Column('client_secret', sa.String(length=255), nullable=True),
    sa.Column('redirect_uri', sa.String(length=255), nullable=False),
    sa.Column('is_confidential', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='security'
    )
    op.create_index(op.f('ix_security_oauth2_clients_client_id'), 'oauth2_clients', ['client_id'], unique=True, schema='security')
    op.create_table('resources',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='security'
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='security'
    )
    op.create_table('frag_etiqueta',
    sa.Column('frag_id', sa.Integer(), nullable=False),
    sa.Column('etiqueta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['etiqueta_id'], ['cegep.etiqueta.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['frag_id'], ['cegep.frag_mis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('frag_id', 'etiqueta_id'),
    schema='cegep'
    )
    op.create_table('grupos_pg',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('grupo', sa.Integer(), nullable=False),
    sa.Column('pg_short', sa.String(length=2), nullable=False),
    sa.ForeignKeyConstraint(['pg_short'], ['posto_grad.short'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='cegep'
    )
    op.create_table('cidades',
    sa.Column('codigo', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('uf', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['uf'], ['estados.uf'], ),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('esf_aer_alocado',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('esfaer_id', sa.SmallInteger(), nullable=False),
    sa.Column('ano_ref', sa.Integer(), nullable=False),
    sa.Column('alocado', sa.Integer(), nullable=False),
    sa.Column('m1', sa.SmallInteger(), nullable=False),
    sa.Column('m2', sa.SmallInteger(), nullable=False),
    sa.Column('m3', sa.SmallInteger(), nullable=False),
    sa.Column('m4', sa.SmallInteger(), nullable=False),
    sa.Column('m5', sa.SmallInteger(), nullable=False),
    sa.Column('m6', sa.SmallInteger(), nullable=False),
    sa.Column('m7', sa.SmallInteger(), nullable=False),
    sa.Column('m8', sa.SmallInteger(), nullable=False),
    sa.Column('m9', sa.SmallInteger(), nullable=False),
    sa.Column('m10', sa.SmallInteger(), nullable=False),
    sa.Column('m11', sa.SmallInteger(), nullable=False),
    sa.Column('m12', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint('alocado % 5 = 0', name='ck_alocado_multiplo_5'),
    sa.CheckConstraint('alocado >= 0', name='ck_alocado_aloc_min'),
    sa.CheckConstraint('ano_ref >= 2020', name='ck_alocado_anoref_min'),
    sa.CheckConstraint('m1 >= 0 AND m1 % 5 = 0', name='ck_aloc_m1'),
    sa.CheckConstraint('m10 >= 0 AND m10 % 5 = 0', name='ck_aloc_m10'),
    sa.CheckConstraint('m11 >= 0 AND m11 % 5 = 0', name='ck_aloc_m11'),
    sa.CheckConstraint('m12 >= 0 AND m12 % 5 = 0', name='ck_aloc_m12'),
    sa.CheckConstraint('m2 >= 0 AND m2 % 5 = 0', name='ck_aloc_m2'),
    sa.CheckConstraint('m3 >= 0 AND m3 % 5 = 0', name='ck_aloc_m3'),
    sa.CheckConstraint('m4 >= 0 AND m4 % 5 = 0', name='ck_aloc_m4'),
    sa.CheckConstraint('m5 >= 0 AND m5 % 5 = 0', name='ck_aloc_m5'),
    sa.CheckConstraint('m6 >= 0 AND m6 % 5 = 0', name='ck_aloc_m6'),
    sa.CheckConstraint('m7 >= 0 AND m7 % 5 = 0', name='ck_aloc_m7'),
    sa.CheckConstraint('m8 >= 0 AND m8 % 5 = 0', name='ck_aloc_m8'),
    sa.CheckConstraint('m9 >= 0 AND m9 % 5 = 0', name='ck_aloc_m9'),
    sa.ForeignKeyConstraint(['esfaer_id'], ['estatistica.esf_aer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='estatistica'
    )
    op.create_table('etapas',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('missao_id', sa.SmallInteger(), nullable=False),
    sa.Column('obs', sa.String(), nullable=True),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('origem', sa.String(length=4), nullable=False),
    sa.Column('destino', sa.String(length=4), nullable=False),
    sa.Column('dep', sa.Time(), nullable=False),
    sa.Column('arr', sa.Time(), nullable=False),
    sa.Column('tvoo', sa.SmallInteger(), sa.Computed("CASE WHEN arr < dep THEN EXTRACT(EPOCH FROM (arr - dep + interval '1 day'))::integer / 60 ELSE EXTRACT(EPOCH FROM (arr - dep))::integer / 60 END", persisted=True), nullable=False),
    sa.Column('anv', sa.String(length=4), nullable=False),
    sa.Column('pousos', sa.SmallInteger(), nullable=False),
    sa.Column('tow', sa.Integer(), nullable=True),
    sa.Column('pax', sa.SmallInteger(), nullable=True),
    sa.Column('carga', sa.SmallInteger(), nullable=True),
    sa.Column('comb', sa.SmallInteger(), nullable=True),
    sa.Column('lub', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('nivel', sa.String(length=3), nullable=True),
    sa.Column('sagem', sa.Boolean(), nullable=False),
    sa.Column('parte1', sa.Boolean(), nullable=False),
    sa.CheckConstraint("nivel ~ '^[0-9]{3}$'", name='ck_etapa_nivel_fl'),
    sa.CheckConstraint('carga >= 0', name='ck_etapa_carga_nn'),
    sa.CheckConstraint('comb > 0', name='ck_etapa_comb_nn'),
    sa.CheckConstraint('lub >= 0', name='ck_etapa_lub_nn'),
    sa.CheckConstraint('pax >= 0', name='ck_etapa_pax_nn'),
    sa.CheckConstraint('pousos >= 0', name='ck_etapa_pousos_nn'),
    sa.CheckConstraint('tow > 0', name='ck_etapa_tow_positivo'),
    sa.CheckConstraint('tvoo % 5 = 0', name='ck_etapa_tvoo_multiplo_5'),
    sa.CheckConstraint('tvoo >= 5', name='ck_etapa_tvoo_min'),
    sa.ForeignKeyConstraint(['anv'], ['aeronaves.matricula'], ),
    sa.ForeignKeyConstraint(['missao_id'], ['estatistica.missao.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='estatistica'
    )
    op.create_table('organizacao_relacoes',
    sa.Column('parent_id', sa.String(length=20), nullable=False),
    sa.Column('child_id', sa.String(length=20), nullable=False),
    sa.CheckConstraint('parent_id <> child_id', name='ck_organizacao_relacoes_sem_autoreferencia'),
    sa.ForeignKeyConstraint(['child_id'], ['organizacoes.sigla'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['organizacoes.sigla'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('parent_id', 'child_id')
    )
    op.create_table('quads_group',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('short', sa.String(), nullable=False),
    sa.Column('long', sa.String(), nullable=False),
    sa.Column('uae', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['uae'], ['organizacoes.sigla'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['security.resources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='security'
    )
    op.create_table('soldos',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('pg', sa.String(length=2), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.CheckConstraint('data_fim IS NULL OR data_inicio < data_fim', name='ck_soldos_data_inicio_antes_fim'),
    sa.CheckConstraint('valor >= 0', name='ck_soldos_valor_nao_negativo'),
    sa.ForeignKeyConstraint(['pg'], ['posto_grad.short'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenants',
    sa.Column('organizacao_id', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organizacao_id'], ['organizacoes.sigla'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('organizacao_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('p_g', sa.String(length=2), nullable=False),
    sa.Column('quadro', sa.String(), nullable=True),
    sa.Column('esp', sa.String(), nullable=True),
    sa.Column('nome_guerra', sa.String(), nullable=False),
    sa.Column('nome_completo', sa.String(), nullable=True),
    sa.Column('id_fab', sa.String(length=6), nullable=True),
    sa.Column('saram', sa.String(length=7), nullable=False),
    sa.Column('unidade', sa.String(length=20), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('telefone', sa.String(length=11), nullable=True),
    sa.Column('email_fab', sa.String(), nullable=True),
    sa.Column('email_pess', sa.String(), nullable=True),
    sa.Column('nasc', sa.Date(), nullable=True),
    sa.Column('ult_promo', sa.Date(), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('ant_rel', sa.Integer(), nullable=True),
    sa.Column('first_login', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['p_g'], ['posto_grad.short'], ),
    sa.ForeignKeyConstraint(['unidade'], ['organizacoes.sigla'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_fab'),
    sa.UniqueConstraint('saram')
    )
    op.create_table('atas_inspecao',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('letra_finalidade', sa.String(length=1), nullable=True),
    sa.Column('data_realizacao', sa.Date(), nullable=True),
    sa.Column('validade_inspsau', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='aeromedica'
    )
    op.create_table('cartoes_saude',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cemal', sa.Date(), nullable=True),
    sa.Column('tovn', sa.Date(), nullable=True),
    sa.Column('imae', sa.Date(), nullable=True),
    sa.Column('prontuario', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    schema='aeromedica'
    )
    op.create_table('comissionamento',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('dep', sa.Boolean(), nullable=False),
    sa.Column('cache_calc', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('data_ab', sa.Date(), nullable=False),
    sa.Column('qtd_aj_ab', sa.Float(), nullable=False),
    sa.Column('valor_aj_ab', sa.Float(), nullable=False),
    sa.Column('data_fc', sa.Date(), nullable=False),
    sa.Column('qtd_aj_fc', sa.Float(), nullable=False),
    sa.Column('valor_aj_fc', sa.Float(), nullable=False),
    sa.Column('dias_cumprir', sa.Integer(), nullable=True),
    sa.Column('doc_prop', sa.String(), nullable=False),
    sa.Column('doc_aut', sa.String(), nullable=False),
    sa.Column('doc_enc', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='cegep'
    )
    op.create_table('dados_bancarios',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('banco', sa.String(), nullable=False),
    sa.Column('codigo_banco', sa.String(), nullable=False),
    sa.Column('agencia', sa.String(), nullable=False),
    sa.Column('conta', sa.String(), nullable=False),
    sa.Column('remuneracao', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('mes_ano', sa.Date(), nullable=True),
    sa.Column('aux_transp', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    schema='cegep'
    )
    op.create_table('grupos_cidade',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('grupo', sa.Integer(), nullable=False),
    sa.Column('cidade_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cidade_id'], ['cidades.codigo'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='cegep'
    )
    op.create_table('pernoite_frag',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('cidade_id', sa.Integer(), nullable=False),
    sa.Column('frag_id', sa.Integer(), nullable=False),
    sa.Column('acrec_desloc', sa.Boolean(), nullable=False),
    sa.Column('data_ini', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('obs', sa.String(), nullable=True),
    sa.Column('meia_diaria', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cidade_id'], ['cidades.codigo'], ),
    sa.ForeignKeyConstraint(['frag_id'], ['cegep.frag_mis.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='cegep'
    )
    op.create_table('users_frag',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('frag_id', sa.Integer(), nullable=False),
    sa.Column('sit', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('p_g', sa.String(length=2), nullable=False),
    sa.ForeignKeyConstraint(['frag_id'], ['cegep.frag_mis.id'], ),
    sa.ForeignKeyConstraint(['p_g'], ['posto_grad.short'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='cegep'
    )
    op.create_table('esf_aer_aloc_hist',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('esf_aer_aloc_id', sa.Integer(), nullable=False),
    sa.Column('aloc_hist', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.CheckConstraint('aloc_hist % 5 = 0', name='ck_aloc_hist_multiplo_5'),
    sa.CheckConstraint('aloc_hist >= 0', name='ck_aloc_hist_min'),
    sa.ForeignKeyConstraint(['esf_aer_aloc_id'], ['estatistica.esf_aer_alocado.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='estatistica'
    )
    op.create_table('heavy_cds_etapa',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('etapa_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=5), nullable=False),
    sa.Column('peso', sa.SmallInteger(), nullable=False),
    sa.Column('dist', sa.SmallInteger(), nullable=False),
    sa.Column('radial', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint("tipo IN ('heavy', 'cds')", name='ck_heavy_cds_tipo'),
    sa.CheckConstraint('dist >= 0', name='ck_heavy_cds_dist_nn'),
    sa.CheckConstraint('peso >= 0', name='ck_heavy_cds_peso_nn'),
    sa.CheckConstraint('radial >= 0 AND radial < 360', name='ck_heavy_cds_radial_range'),
    sa.ForeignKeyConstraint(['etapa_id'], ['estatistica.etapas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='estatistica'
    )
    op.create_index(op.f('ix_estatistica_heavy_cds_etapa_etapa_id'), 'heavy_cds_etapa', ['etapa_id'], unique=False, schema='estatistica')
    op.create_table('oi_etapa',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('etapa_id', sa.Integer(), nullable=False),
    sa.Column('esf_aer_id', sa.SmallInteger(), nullable=False),
    sa.Column('tvoo', sa.SmallInteger(), nullable=False),
    sa.Column('reg', sa.String(length=1), nullable=False),
    sa.Column('tipo_missao_id', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint('tvoo % 5 = 0', name='ck_oi_etapa_tvoo_multiplo_5'),
    sa.CheckConstraint('tvoo >= 5', name='ck_oi_etapa_tvoo_min'),
    sa.ForeignKeyConstraint(['esf_aer_id'], ['estatistica.esf_aer.id'], ),
    sa.ForeignKeyConstraint(['etapa_id'], ['estatistica.etapas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tipo_missao_id'], ['estatistica.tipo_missao.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='estatistica'
    )
    op.create_index(op.f('ix_estatistica_oi_etapa_etapa_id'), 'oi_etapa', ['etapa_id'], unique=False, schema='estatistica')
    op.create_table('pqd_etapa',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('etapa_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=5), nullable=False),
    sa.Column('qtd', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint("tipo IN ('VTC', 'LV', 'PREC', 'LIVRE')", name='ck_pqd_tipo'),
    sa.CheckConstraint('qtd >= 0', name='ck_pqd_qtd_nn'),
    sa.ForeignKeyConstraint(['etapa_id'], ['estatistica.etapas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='estatistica'
    )
    op.create_index(op.f('ix_estatistica_pqd_etapa_etapa_id'), 'pqd_etapa', ['etapa_id'], unique=False, schema='estatistica')
    op.create_table('revo_etapa',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('etapa_id', sa.Integer(), nullable=False),
    sa.Column('comb_transf', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint('comb_transf >= 0', name='ck_revo_comb_transf_nn'),
    sa.ForeignKeyConstraint(['etapa_id'], ['estatistica.etapas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='estatistica'
    )
    op.create_index(op.f('ix_estatistica_revo_etapa_etapa_id'), 'revo_etapa', ['etapa_id'], unique=False, schema='estatistica')
    op.create_table('grupos_loc_esp',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('cidade_id', sa.Integer(), nullable=False),
    sa.Column('grupo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cidade_id'], ['cidades.codigo'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('indisps',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_start', sa.Date(), nullable=False),
    sa.Column('date_end', sa.Date(), nullable=False),
    sa.Column('mtv', sa.String(), nullable=False),
    sa.Column('obs', sa.String(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cartoes',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ptai_validade', sa.Date(), nullable=True),
    sa.Column('tai_s_validade', sa.Date(), nullable=True),
    sa.Column('tai_s1_validade', sa.Date(), nullable=True),
    sa.Column('cvi_validade', sa.Date(), nullable=True),
    sa.Column('hab_espanhol', sa.String(length=2), nullable=True),
    sa.Column('val_espanhol', sa.Date(), nullable=True),
    sa.Column('hab_ingles', sa.String(length=2), nullable=True),
    sa.Column('val_ingles', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    schema='instrucao'
    )
    op.create_table('passaportes',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('passaporte', sa.String(length=20), nullable=True),
    sa.Column('data_expedicao_passaporte', sa.Date(), nullable=True),
    sa.Column('validade_passaporte', sa.Date(), nullable=True),
    sa.Column('visa', sa.String(length=20), nullable=True),
    sa.Column('data_expedicao_visa', sa.Date(), nullable=True),
    sa.Column('validade_visa', sa.Date(), nullable=True),
    sa.CheckConstraint('data_expedicao_passaporte IS NULL OR validade_passaporte IS NULL OR data_expedicao_passaporte <= validade_passaporte', name='ck_passaporte_expedicao_le_validade'),
    sa.CheckConstraint('data_expedicao_visa IS NULL OR validade_visa IS NULL OR data_expedicao_visa <= validade_visa', name='ck_visa_expedicao_le_validade'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    schema='inteligencia'
    )
    op.create_table('aerodromos',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('codigo_icao', sa.String(), nullable=False),
    sa.Column('codigo_iata', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('elevacao', sa.Float(), nullable=False),
    sa.Column('pais', sa.String(), nullable=False),
    sa.Column('utc', sa.Integer(), nullable=False),
    sa.Column('base_aerea', sa.JSON(), nullable=True),
    sa.Column('codigo_cidade', sa.Integer(), nullable=True),
    sa.Column('cidade_manual', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['codigo_cidade'], ['cidades.codigo'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_icao'),
    schema='nav'
    )
    op.create_table('om_ordens_missao',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('matricula_anv', sa.String(length=4), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('projeto', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('campos_especiais', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('uae', sa.String(length=20), nullable=False),
    sa.Column('esf_aer', sa.Integer(), nullable=False),
    sa.Column('doc_ref', sa.String(length=100), nullable=True),
    sa.Column('data_saida', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['matricula_anv'], ['aeronaves.matricula'], ),
    sa.ForeignKeyConstraint(['uae'], ['organizacoes.sigla'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promo_users',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('p_g', sa.String(length=2), nullable=False),
    sa.Column('data_promo', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['p_g'], ['posto_grad.short'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'data_promo', name='uq_promo_users_user_data'),
    sa.UniqueConstraint('user_id', 'p_g', name='uq_promo_users_user_pg')
    )
    op.create_table('quads_type',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('short', sa.String(), nullable=False),
    sa.Column('long', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['quads_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oauth2_authorization_codes',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('code_challenge', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('code_challenge_method', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['security.oauth2_clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='security'
    )
    op.create_index(op.f('ix_security_oauth2_authorization_codes_code'), 'oauth2_authorization_codes', ['code'], unique=True, schema='security')
    op.create_table('oauth2_tokens',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('access_token', sa.String(length=255), nullable=False),
    sa.Column('refresh_token', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['security.oauth2_clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='security'
    )
    op.create_index(op.f('ix_security_oauth2_tokens_access_token'), 'oauth2_tokens', ['access_token'], unique=True, schema='security')
    op.create_index(op.f('ix_security_oauth2_tokens_refresh_token'), 'oauth2_tokens', ['refresh_token'], unique=True, schema='security')
    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['security.permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['security.roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='security'
    )
    op.create_table('user_action_logs',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource', sa.String(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('before', sa.String(), nullable=True),
    sa.Column('after', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='security'
    )
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('organizacao_id', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['organizacao_id'], ['tenants.organizacao_id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['security.roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'organizacao_id', name='uq_user_roles_user_org', postgresql_nulls_not_distinct=True),
    schema='security'
    )
    op.create_table('crm_certificados',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('data_realizacao', sa.Date(), nullable=True),
    sa.Column('data_validade', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    schema='seg_voo'
    )
    op.create_table('tripulantes',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trig', sa.String(length=3), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('uae', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['uae'], ['organizacoes.sigla'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trip_etapa',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('etapa_id', sa.Integer(), nullable=False),
    sa.Column('func', sa.String(length=3), nullable=False),
    sa.Column('func_bordo', sa.String(length=2), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['etapa_id'], ['estatistica.etapas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['tripulantes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='estatistica'
    )
    op.create_index(op.f('ix_estatistica_trip_etapa_etapa_id'), 'trip_etapa', ['etapa_id'], unique=False, schema='estatistica')
    op.create_table('om_etapas',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('ordem_id', sa.Integer(), nullable=False),
    sa.Column('dt_dep', sa.DateTime(timezone=True), nullable=False),
    sa.Column('origem', sa.String(length=10), nullable=False),
    sa.Column('dest', sa.String(length=10), nullable=False),
    sa.Column('dt_arr', sa.DateTime(timezone=True), nullable=False),
    sa.Column('alternativa', sa.String(length=10), nullable=False),
    sa.Column('tvoo_etp', sa.Integer(), nullable=False),
    sa.Column('tvoo_alt', sa.Integer(), nullable=False),
    sa.Column('qtd_comb', sa.Integer(), nullable=False),
    sa.Column('esf_aer', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['ordem_id'], ['om_ordens_missao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('om_etiqueta',
    sa.Column('ordem_id', sa.Integer(), nullable=False),
    sa.Column('etiqueta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['etiqueta_id'], ['om_etiquetas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ordem_id'], ['om_ordens_missao.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ordem_id', 'etiqueta_id')
    )
    op.create_table('om_tripulacao',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('ordem_id', sa.Integer(), nullable=False),
    sa.Column('tripulante_id', sa.Integer(), nullable=False),
    sa.Column('funcao', sa.String(length=10), nullable=False),
    sa.Column('p_g', sa.String(length=2), nullable=False),
    sa.ForeignKeyConstraint(['ordem_id'], ['om_ordens_missao.id'], ),
    sa.ForeignKeyConstraint(['p_g'], ['posto_grad.short'], ),
    sa.ForeignKeyConstraint(['tripulante_id'], ['tripulantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quad',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Date(), nullable=True),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['tripulantes.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['quads_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quads_func',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('func', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['quads_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type_id', 'func', name='uq_quads_func_type_func')
    )
    op.create_table('trip_funcs',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('func', sa.String(length=3), nullable=False),
    sa.Column('oper', sa.String(length=2), nullable=False),
    sa.Column('proj', sa.String(), nullable=False),
    sa.Column('data_op', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['tripulantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trip_funcs')
    op.drop_table('quads_func')
    op.drop_table('quad')
    op.drop_table('om_tripulacao')
    op.drop_table('om_etiqueta')
    op.drop_table('om_etapas')
    op.drop_index(op.f('ix_estatistica_trip_etapa_etapa_id'), table_name='trip_etapa', schema='estatistica')
    op.drop_table('trip_etapa', schema='estatistica')
    op.drop_table('tripulantes')
    op.drop_table('crm_certificados', schema='seg_voo')
    op.drop_table('user_roles', schema='security')
    op.drop_table('user_action_logs', schema='security')
    op.drop_table('role_permissions', schema='security')
    op.drop_index(op.f('ix_security_oauth2_tokens_refresh_token'), table_name='oauth2_tokens', schema='security')
    op.drop_index(op.f('ix_security_oauth2_tokens_access_token'), table_name='oauth2_tokens', schema='security')
    op.drop_table('oauth2_tokens', schema='security')
    op.drop_index(op.f('ix_security_oauth2_authorization_codes_code'), table_name='oauth2_authorization_codes', schema='security')
    op.drop_table('oauth2_authorization_codes', schema='security')
    op.drop_table('quads_type')
    op.drop_table('promo_users')
    op.drop_table('om_ordens_missao')
    op.drop_table('aerodromos', schema='nav')
    op.drop_table('passaportes', schema='inteligencia')
    op.drop_table('cartoes', schema='instrucao')
    op.drop_table('indisps')
    op.drop_table('grupos_loc_esp')
    op.drop_index(op.f('ix_estatistica_revo_etapa_etapa_id'), table_name='revo_etapa', schema='estatistica')
    op.drop_table('revo_etapa', schema='estatistica')
    op.drop_index(op.f('ix_estatistica_pqd_etapa_etapa_id'), table_name='pqd_etapa', schema='estatistica')
    op.drop_table('pqd_etapa', schema='estatistica')
    op.drop_index(op.f('ix_estatistica_oi_etapa_etapa_id'), table_name='oi_etapa', schema='estatistica')
    op.drop_table('oi_etapa', schema='estatistica')
    op.drop_index(op.f('ix_estatistica_heavy_cds_etapa_etapa_id'), table_name='heavy_cds_etapa', schema='estatistica')
    op.drop_table('heavy_cds_etapa', schema='estatistica')
    op.drop_table('esf_aer_aloc_hist', schema='estatistica')
    op.drop_table('users_frag', schema='cegep')
    op.drop_table('pernoite_frag', schema='cegep')
    op.drop_table('grupos_cidade', schema='cegep')
    op.drop_table('dados_bancarios', schema='cegep')
    op.drop_table('comissionamento', schema='cegep')
    op.drop_table('cartoes_saude', schema='aeromedica')
    op.drop_table('atas_inspecao', schema='aeromedica')
    op.drop_table('users')
    op.drop_table('tenants')
    op.drop_table('soldos')
    op.drop_table('permissions', schema='security')
    op.drop_table('quads_group')
    op.drop_table('organizacao_relacoes')
    op.drop_table('etapas', schema='estatistica')
    op.drop_table('esf_aer_alocado', schema='estatistica')
    op.drop_table('cidades')
    op.drop_table('grupos_pg', schema='cegep')
    op.drop_table('frag_etiqueta', schema='cegep')
    op.drop_table('roles', schema='security')
    op.drop_table('resources', schema='security')
    op.drop_index(op.f('ix_security_oauth2_clients_client_id'), table_name='oauth2_clients', schema='security')
    op.drop_table('oauth2_clients', schema='security')
    op.drop_table('posto_grad')
    op.drop_table('organizacoes')
    op.drop_table('om_etiquetas')
    op.drop_table('tipo_missao', schema='estatistica')
    op.drop_table('missao', schema='estatistica')
    op.drop_table('esf_aer', schema='estatistica')
    op.drop_table('estados')
    op.drop_table('valor_diarias', schema='cegep')
    op.drop_table('orcamento_anual', schema='cegep')
    op.drop_table('frag_mis', schema='cegep')
    op.drop_table('etiqueta', schema='cegep')
    op.drop_table('aeronaves')
    # squash: schemas derivados automaticamente
    for _schema in (
        'seg_voo',
        'security',
        'nav',
        'inteligencia',
        'instrucao',
        'estatistica',
        'cegep',
        'aeromedica',
    ):
        op.execute(f'DROP SCHEMA IF EXISTS {_schema}')
    # ### end Alembic commands ###
