"""add seg_voo schema and crm_certificados table

Revision ID: 11b4c104620e
Revises: 3367bac2b2e2
Create Date: 2026-03-20 15:47:32.801677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11b4c104620e'
down_revision: Union[str, None] = '3367bac2b2e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute('CREATE SCHEMA IF NOT EXISTS seg_voo')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crm_certificados',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('data_realizacao', sa.Date(), nullable=True),
    sa.Column('data_validade', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    schema='seg_voo'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crm_certificados', schema='seg_voo')
    op.execute('DROP SCHEMA IF EXISTS seg_voo')
    # ### end Alembic commands ###
