"""ajustando f_key users pg para posto_grad

Revision ID: 121a6b950ed5
Revises: a00cfce1139e
Create Date: 2025-01-27 14:15:39.401939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '121a6b950ed5'
down_revision: Union[str, None] = 'a00cfce1139e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'posto_grad', ['id'])
    op.alter_column('users', 'p_g',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.create_foreign_key(None, 'users', 'posto_grad', ['p_g'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'p_g',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    op.drop_constraint(None, 'posto_grad', type_='unique')
    # ### end Alembic commands ###
