"""remove_prox_insp_from_aeronaves

Revision ID: 1566ae06b25b
Revises: fad4c748fc3e
Create Date: 2026-02-18 19:04:27.840839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1566ae06b25b'
down_revision: Union[str, None] = 'fad4c748fc3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aeronaves', 'prox_insp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aeronaves', sa.Column('prox_insp', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
