"""tabela soldos

Revision ID: 170e8c2eeae8
Revises: a756c5e9920e
Create Date: 2025-07-18 14:29:17.514576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '170e8c2eeae8'
down_revision: Union[str, None] = 'a756c5e9920e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('soldos',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('pg', sa.String(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['pg'], ['posto_grad.short'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('posto_grad', 'soldo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posto_grad', sa.Column('soldo', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_table('soldos')
    # ### end Alembic commands ###
