"""aeromedica

Revision ID: 1a59be932831
Revises: 4e24669e6347
Create Date: 2026-03-18 06:56:12.385835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a59be932831'
down_revision: Union[str, None] = '4e24669e6347'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA IF NOT EXISTS aeromedica')
    
    op.create_table('cartoes_saude',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cemal', sa.Date(), nullable=True),
    sa.Column('ag_cemal', sa.Date(), nullable=True),
    sa.Column('tovn', sa.Date(), nullable=True),
    sa.Column('imae', sa.Date(), nullable=True),
    sa.Column('prontuario', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),

    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    schema='aeromedica'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cartoes_saude', schema='aeromedica')

    op.execute('DROP SCHEMA IF EXISTS aeromedica')
    # ### end Alembic commands ###
