"""inserindo uae em quadsGroup

Revision ID: 1e3721fd4a56
Revises: 37152b40181b
Create Date: 2025-01-30 10:33:00.024249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e3721fd4a56'
down_revision: Union[str, None] = '37152b40181b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quads_group', sa.Column('uae', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quads_group', 'uae')
    # ### end Alembic commands ###
