"""modulo operacoes

Revision ID: 23feef66fb2d
Revises: 0c4c4b16398e
Create Date: 2026-06-08 13:29:38.082487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23feef66fb2d'
down_revision: Union[str, None] = '0c4c4b16398e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projetos_anvs',
    sa.Column('id_projeto', sa.String(length=10), nullable=False),
    sa.Column('modelo', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id_projeto'),
    sa.UniqueConstraint('modelo', name='uq_projetos_anvs_modelo')
    )
    # Seed inicial: único projeto/modelo conhecido. Necessário antes de
    # adicionar aeronaves.projeto NOT NULL (server_default 'C8' backfilla
    # as linhas existentes, que precisam satisfazer a FK).
    op.execute(
        "INSERT INTO projetos_anvs (id_projeto, modelo) "
        "VALUES ('C8', 'kc-390')"
    )
    op.create_table('operacoes',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('cidade_id', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('uae', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('documento_diretriz', sa.String(length=100), nullable=True),
    sa.Column('obs', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('planejada', 'andamento', 'encerrada', 'cancelada')", name='ck_operacao_status'),
    sa.CheckConstraint("tipo IN ('operacao', 'manobra', 'exercicio')", name='ck_operacao_tipo'),
    sa.CheckConstraint('data_fim >= data_inicio', name='ck_operacao_periodo'),
    sa.ForeignKeyConstraint(['cidade_id'], ['cidades.codigo'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['uae'], ['tenants.organizacao_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uae', 'nome', name='uq_operacao_uae_nome'),
    sa.UniqueConstraint('uae', 'numero', name='uq_operacao_uae_numero')
    )
    op.create_table('operacao_etapa',
    sa.Column('etapa_id', sa.Integer(), nullable=False),
    sa.Column('operacao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['etapa_id'], ['estatistica.etapas.id'], name='fk_operacao_etapa_etapa', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operacao_id'], ['operacoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('etapa_id')
    )
    op.create_index(op.f('ix_operacao_etapa_operacao_id'), 'operacao_etapa', ['operacao_id'], unique=False)
    op.create_table('operacao_pessoal',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('operacao_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('func', sa.String(length=80), nullable=False),
    sa.Column('om', sa.String(length=60), nullable=False),
    sa.Column('data_ingresso', sa.Date(), nullable=False),
    sa.Column('data_regresso', sa.Date(), nullable=False),
    sa.CheckConstraint('data_regresso >= data_ingresso', name='ck_operacao_pessoal_periodo'),
    sa.ForeignKeyConstraint(['operacao_id'], ['operacoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operacao_pessoal_operacao_id'), 'operacao_pessoal', ['operacao_id'], unique=False)
    op.add_column('aeronaves', sa.Column('projeto', sa.String(length=10), server_default='C8', nullable=False))
    op.create_foreign_key('fk_aeronaves_projeto', 'aeronaves', 'projetos_anvs', ['projeto'], ['id_projeto'], onupdate='CASCADE')
    # trip_funcs.proj já guarda o modelo ('kc-390'), que casa com o seed
    # acima — FK valida sem backfill.
    op.create_foreign_key('fk_trip_funcs_proj', 'trip_funcs', 'projetos_anvs', ['proj'], ['modelo'], onupdate='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_trip_funcs_proj', 'trip_funcs', type_='foreignkey')
    op.drop_constraint('fk_aeronaves_projeto', 'aeronaves', type_='foreignkey')
    op.drop_column('aeronaves', 'projeto')
    op.drop_index(op.f('ix_operacao_pessoal_operacao_id'), table_name='operacao_pessoal')
    op.drop_table('operacao_pessoal')
    op.drop_index(op.f('ix_operacao_etapa_operacao_id'), table_name='operacao_etapa')
    op.drop_table('operacao_etapa')
    op.drop_table('operacoes')
    op.drop_table('projetos_anvs')
    # ### end Alembic commands ###
