"""estatistica feature

Revision ID: 2880ea0826c6
Revises: 1566ae06b25b
Create Date: 2026-03-02 21:19:46.352408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2880ea0826c6'
down_revision: Union[str, None] = '1566ae06b25b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA IF NOT EXISTS estatistica')
    op.create_table('esf_aer',
    sa.Column('id', sa.SmallInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('modelo', sa.String(), nullable=False),
    sa.Column('grupo', sa.String(), nullable=False),
    sa.Column('prog', sa.String(), nullable=False),
    sa.Column('sub_prog', sa.String(), nullable=True),
    sa.Column('aplicacao', sa.String(), nullable=True),
    sa.Column('descricao', sa.String(), sa.Computed("grupo || ' ' || prog || COALESCE(' ' || sub_prog, '') || COALESCE(' ' || aplicacao, '')", persisted=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='estatistica'
    )
    op.create_table('missao',
    sa.Column('id', sa.SmallInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('titulo', sa.String(), nullable=True),
    sa.Column('obs', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='estatistica'
    )
    op.create_table('tipo_missao',
    sa.Column('id', sa.SmallInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('cod', sa.String(length=4), nullable=False),
    sa.Column('desc', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='estatistica'
    )
    op.create_table('esf_aer_alocado',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('esfaer_id', sa.SmallInteger(), nullable=False),
    sa.Column('ano_ref', sa.Integer(), nullable=False),
    sa.Column('alocado', sa.Integer(), nullable=False),
    sa.CheckConstraint('alocado % 5 = 0', name='ck_alocado_multiplo_5'),
    sa.CheckConstraint('alocado >= 0', name='ck_alocado_aloc_min'),
    sa.CheckConstraint('ano_ref >= 2020', name='ck_alocado_anoref_min'),
    sa.ForeignKeyConstraint(['esfaer_id'], ['estatistica.esf_aer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='estatistica'
    )
    op.create_table('etapas',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('missao_id', sa.SmallInteger(), nullable=False),
    sa.Column('obs', sa.String(), nullable=True),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('origem', sa.String(length=4), nullable=False),
    sa.Column('destino', sa.String(length=4), nullable=False),
    sa.Column('dep', sa.Time(), nullable=False),
    sa.Column('arr', sa.Time(), nullable=False),
    sa.Column('tvoo', sa.SmallInteger(), sa.Computed("CASE WHEN arr < dep THEN EXTRACT(EPOCH FROM (arr - dep + interval '1 day'))::integer / 60 ELSE EXTRACT(EPOCH FROM (arr - dep))::integer / 60 END", persisted=True), nullable=False),
    sa.Column('anv', sa.String(length=4), nullable=False),
    sa.Column('pousos', sa.SmallInteger(), nullable=False),
    sa.Column('tow', sa.Integer(), nullable=True),
    sa.Column('pax', sa.SmallInteger(), nullable=True),
    sa.Column('carga', sa.SmallInteger(), nullable=True),
    sa.Column('comb', sa.SmallInteger(), nullable=True),
    sa.Column('lub', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('nivel', sa.String(length=3), nullable=True),
    sa.Column('sagem', sa.Boolean(), nullable=False),
    sa.Column('parte1', sa.Boolean(), nullable=False),
    sa.CheckConstraint("nivel ~ '^[0-9]{3}$'", name='ck_etapa_nivel_fl'),
    sa.CheckConstraint('carga >= 0', name='ck_etapa_carga_nn'),
    sa.CheckConstraint('comb > 0', name='ck_etapa_comb_nn'),
    sa.CheckConstraint('lub >= 0', name='ck_etapa_lub_nn'),
    sa.CheckConstraint('pax >= 0', name='ck_etapa_pax_nn'),
    sa.CheckConstraint('pousos >= 0', name='ck_etapa_pousos_nn'),
    sa.CheckConstraint('tow > 0', name='ck_etapa_tow_positivo'),
    sa.CheckConstraint('tvoo % 5 = 0', name='ck_etapa_tvoo_multiplo_5'),
    sa.CheckConstraint('tvoo >= 5', name='ck_etapa_tvoo_min'),
    sa.ForeignKeyConstraint(['anv'], ['aeronaves.matricula'], ),
    sa.ForeignKeyConstraint(['missao_id'], ['estatistica.missao.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='estatistica'
    )
    op.create_table('esf_aer_aloc_hist',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('esf_aer_aloc_id', sa.Integer(), nullable=False),
    sa.Column('aloc_hist', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.CheckConstraint('aloc_hist % 5 = 0', name='ck_aloc_hist_multiplo_5'),
    sa.CheckConstraint('aloc_hist >= 0', name='ck_aloc_hist_min'),
    sa.ForeignKeyConstraint(['esf_aer_aloc_id'], ['estatistica.esf_aer_alocado.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='estatistica'
    )
    op.create_table('oi_etapa',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('etapa_id', sa.Integer(), nullable=False),
    sa.Column('esf_aer_id', sa.SmallInteger(), nullable=False),
    sa.Column('tvoo', sa.SmallInteger(), nullable=False),
    sa.Column('reg', sa.String(length=1), nullable=False),
    sa.Column('tipo_missao_id', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint('tvoo % 5 = 0', name='ck_oi_etapa_tvoo_multiplo_5'),
    sa.CheckConstraint('tvoo >= 5', name='ck_oi_etapa_tvoo_min'),
    sa.ForeignKeyConstraint(['esf_aer_id'], ['estatistica.esf_aer.id'], ),
    sa.ForeignKeyConstraint(['etapa_id'], ['estatistica.etapas.id'], ),
    sa.ForeignKeyConstraint(['tipo_missao_id'], ['estatistica.tipo_missao.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='estatistica'
    )
    op.create_table('trip_etapa',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('etapa_id', sa.Integer(), nullable=False),
    sa.Column('func', sa.String(length=3), nullable=False),
    sa.Column('func_bordo', sa.String(length=2), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['etapa_id'], ['estatistica.etapas.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['tripulantes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='estatistica'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trip_etapa', schema='estatistica')
    op.drop_table('oi_etapa', schema='estatistica')
    op.drop_table('esf_aer_aloc_hist', schema='estatistica')
    op.drop_table('etapas', schema='estatistica')
    op.drop_table('esf_aer_alocado', schema='estatistica')
    op.drop_table('tipo_missao', schema='estatistica')
    op.drop_table('missao', schema='estatistica')
    op.drop_table('esf_aer', schema='estatistica')
    op.execute('DROP SCHEMA IF EXISTS estatistica')
    # ### end Alembic commands ###
