"""add_telefone_to_users

Revision ID: 3367bac2b2e2
Revises: 10c89e0ce609
Create Date: 2026-03-20 14:08:37.002967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3367bac2b2e2'
down_revision: Union[str, None] = '10c89e0ce609'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telefone', sa.String(length=11), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'telefone')
    # ### end Alembic commands ###
