"""add tabela etiqueta

Revision ID: 349bc7a3af18
Revises: a2a9d3124ce9
Create Date: 2025-12-22 08:31:00.225328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '349bc7a3af18'
down_revision: Union[str, None] = 'a2a9d3124ce9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etiqueta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cor', sa.String(length=7), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='cegep'
    )
    op.create_table('frag_etiqueta',
    sa.Column('frag_id', sa.Integer(), nullable=False),
    sa.Column('etiqueta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['etiqueta_id'], ['cegep.etiqueta.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['frag_id'], ['cegep.frag_mis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('frag_id', 'etiqueta_id'),
    schema='cegep'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('frag_etiqueta', schema='cegep')
    op.drop_table('etiqueta', schema='cegep')
    # ### end Alembic commands ###
