"""Add labels and associate with OM

Revision ID: 425b0b0c16eb
Revises: 8e45a036c6f5
Create Date: 2025-12-31 09:12:50.520368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '425b0b0c16eb'
down_revision: Union[str, None] = '8e45a036c6f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etiquetas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cor', sa.String(length=7), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ordem_etiqueta',
    sa.Column('ordem_id', sa.Integer(), nullable=False),
    sa.Column('etiqueta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['etiqueta_id'], ['etiquetas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ordem_id'], ['ordens_missao.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ordem_id', 'etiqueta_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ordem_etiqueta')
    op.drop_table('etiquetas')
    # ### end Alembic commands ###
