"""convert_serial_to_identity

Revision ID: 490dffb3f8c9
Revises: ca7ac9e9e2e6
Create Date: 2025-12-28

Converte colunas SERIAL para IDENTITY para consistencia do banco.
Tabelas afetadas:
- security.oauth2_authorization_codes
- security.oauth2_clients
- security.oauth2_tokens
- security.user_action_logs
- cegep.etiqueta
"""

from typing import Sequence, Union

from alembic import op


revision: str = '490dffb3f8c9'
down_revision: Union[str, None] = 'ca7ac9e9e2e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Tabelas a converter: (schema, tabela, sequencia)
TABLES_TO_CONVERT = [
    ('security', 'oauth2_authorization_codes', 'oauth2_authorization_codes_id_seq'),
    ('security', 'oauth2_clients', 'oauth2_clients_id_seq'),
    ('security', 'oauth2_tokens', 'oauth2_tokens_id_seq'),
    ('security', 'user_action_logs', 'user_action_logs_id_seq'),
    ('cegep', 'etiqueta', 'etiqueta_id_seq'),
]


def upgrade() -> None:
    """Converte SERIAL para IDENTITY."""
    for schema, table, seq_name in TABLES_TO_CONVERT:
        full_table = f'{schema}.{table}'
        full_seq = f'{schema}.{seq_name}'

        # 1. Obter o proximo valor da sequencia
        # 2. Remover o default da coluna
        # 3. Dropar a sequencia
        # 4. Adicionar IDENTITY
        # 5. Reiniciar o contador

        op.execute(f"""
            DO $$
            DECLARE
                next_val bigint;
            BEGIN
                -- Obter proximo valor da sequencia
                SELECT COALESCE(MAX(id), 0) + 1 INTO next_val FROM {full_table};

                -- Remover default da coluna
                ALTER TABLE {full_table} ALTER COLUMN id DROP DEFAULT;

                -- Dropar a sequencia
                DROP SEQUENCE IF EXISTS {full_seq};

                -- Adicionar IDENTITY
                ALTER TABLE {full_table}
                    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

                -- Reiniciar contador do IDENTITY
                EXECUTE format(
                    'ALTER TABLE {full_table} ALTER COLUMN id RESTART WITH %s',
                    next_val
                );
            END $$;
        """)


def downgrade() -> None:
    """Reverte IDENTITY para SERIAL."""
    for schema, table, seq_name in TABLES_TO_CONVERT:
        full_table = f'{schema}.{table}'
        full_seq = f'{schema}.{seq_name}'

        op.execute(f"""
            DO $$
            DECLARE
                next_val bigint;
            BEGIN
                -- Obter proximo valor
                SELECT COALESCE(MAX(id), 0) + 1 INTO next_val FROM {full_table};

                -- Remover IDENTITY
                ALTER TABLE {full_table}
                    ALTER COLUMN id DROP IDENTITY IF EXISTS;

                -- Criar sequencia
                EXECUTE format('CREATE SEQUENCE {full_seq} START WITH %s', next_val);

                -- Setar default para usar a sequencia
                ALTER TABLE {full_table}
                    ALTER COLUMN id SET DEFAULT nextval('{full_seq}');

                -- Associar sequencia a coluna
                ALTER SEQUENCE {full_seq} OWNED BY {full_table}.id;
            END $$;
        """)
