"""ajuste tabela tripulantes

Revision ID: 4d9e020b1122
Revises: 
Create Date: 2024-08-07 14:44:53.943317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d9e020b1122'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('quad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('nacional', 'local', 'desloc', 'sobr', 'sar', name='quadtype'), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tripulantes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trig', sa.String(), nullable=False),
    sa.Column('func', sa.Enum('mc', 'lm', 'tf', 'os', 'oe', name='funclist'), nullable=False),
    sa.Column('oper', sa.Enum('AL', 'BA', 'OP', 'IN', name='operlist'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('trig'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tripulantes')
    op.drop_table('quad')
    op.drop_table('users')
    # ### end Alembic commands ###
