"""add cascade delete to oi_etapa and trip_etapa

Revision ID: 4e24669e6347
Revises: 2880ea0826c6
Create Date: 2026-03-08 12:46:12.040499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e24669e6347'
down_revision: Union[str, None] = '2880ea0826c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('oi_etapa_etapa_id_fkey'), 'oi_etapa', schema='estatistica', type_='foreignkey')
    op.create_foreign_key(None, 'oi_etapa', 'etapas', ['etapa_id'], ['id'], source_schema='estatistica', referent_schema='estatistica', ondelete='CASCADE')
    op.drop_constraint(op.f('trip_etapa_etapa_id_fkey'), 'trip_etapa', schema='estatistica', type_='foreignkey')
    op.create_foreign_key(None, 'trip_etapa', 'etapas', ['etapa_id'], ['id'], source_schema='estatistica', referent_schema='estatistica', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trip_etapa', schema='estatistica', type_='foreignkey')
    op.create_foreign_key(op.f('trip_etapa_etapa_id_fkey'), 'trip_etapa', 'etapas', ['etapa_id'], ['id'], source_schema='estatistica', referent_schema='estatistica')
    op.drop_constraint(None, 'oi_etapa', schema='estatistica', type_='foreignkey')
    op.create_foreign_key(op.f('oi_etapa_etapa_id_fkey'), 'oi_etapa', 'etapas', ['etapa_id'], ['id'], source_schema='estatistica', referent_schema='estatistica')
    # ### end Alembic commands ###
