"""inserindo QuadsFunc

Revision ID: 5860a920441a
Revises: a18c8c2f1b2f
Create Date: 2025-02-11 10:24:06.780272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5860a920441a'
down_revision: Union[str, None] = 'a18c8c2f1b2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quads_func',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('func', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['quads_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_column('quads_type', 'exclude')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quads_type', sa.Column('exclude', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.drop_table('quads_func')
    # ### end Alembic commands ###
