"""passaporte local_passaporte custodia fisica

Revision ID: 605c751aabf4
Revises: 677a102f3335
Create Date: 2026-08-24 15:49:22.584398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '605c751aabf4'
down_revision: Union[str, None] = '677a102f3335'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('passaportes', sa.Column('local_passaporte', sa.String(length=20), server_default=sa.text("'secao'"), nullable=False), schema='inteligencia')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('passaportes', 'local_passaporte', schema='inteligencia')
    # ### end Alembic commands ###
