"""add unique constraint quads_func type_func

Revision ID: 644c5a6b323d
Revises: 6680e240f301
Create Date: 2026-06-02 18:52:57.706313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '644c5a6b323d'
down_revision: Union[str, None] = '6680e240f301'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Limpa duplicados legados (mesmo type_id + func) antes de criar a
    # constraint, mantendo a linha de menor id. Sem isso, a criação da
    # constraint falha em bases com dados duplicados (dev e prod).
    op.execute(
        """
        DELETE FROM quads_func a
        USING quads_func b
        WHERE a.type_id = b.type_id
          AND a.func = b.func
          AND a.id > b.id
        """
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_quads_func_type_func', 'quads_func', ['type_id', 'func'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_quads_func_type_func', 'quads_func', type_='unique')
    # ### end Alembic commands ###
