"""add_is_sim_to_aeronaves

Revision ID: 65c2476a7f97
Revises: e537af81935e
Create Date: 2026-03-27 08:25:05.777428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65c2476a7f97'
down_revision: Union[str, None] = 'e537af81935e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'aeronaves',
        sa.Column(
            'is_sim',
            sa.Boolean(),
            nullable=False,
            server_default='false',
        ),
    )
    op.execute(
        "UPDATE aeronaves SET is_sim = TRUE WHERE matricula = '2850'"
    )
    op.alter_column('aeronaves', 'is_sim', server_default=None)
    op.add_column(
        'passaportes',
        sa.Column('visa', sa.String(length=20), nullable=True),
        schema='inteligencia',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('passaportes', 'visa', schema='inteligencia')
    op.drop_column('aeronaves', 'is_sim')
    # ### end Alembic commands ###
