"""remove ag_cemal

Revision ID: 6680e240f301
Revises: 68f232822932
Create Date: 2026-06-02 12:22:38.349027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6680e240f301'
down_revision: Union[str, None] = '68f232822932'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cartoes_saude', 'ag_cemal', schema='aeromedica')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cartoes_saude', sa.Column('ag_cemal', sa.DATE(), autoincrement=False, nullable=True), schema='aeromedica')
    # ### end Alembic commands ###
