"""add tema column to tenants

Revision ID: 73d561516514
Revises: 91af20b1cca2
Create Date: 2026-07-08 11:46:28.174940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73d561516514'
down_revision: Union[str, None] = '91af20b1cca2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('tema', sa.String(length=20), server_default=sa.text("'red'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'tema')
    # ### end Alembic commands ###
