"""dados bancarios

Revision ID: 7c95b11b6c7b
Revises: 8ef9dcb8bc9a
Create Date: 2025-11-21 19:21:39.235791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c95b11b6c7b'
down_revision: Union[str, None] = '8ef9dcb8bc9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dados_bancarios',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('banco', sa.String(), nullable=False),
    sa.Column('codigo_banco', sa.String(), nullable=False),
    sa.Column('agencia', sa.String(), nullable=False),
    sa.Column('conta', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    schema='cegep'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dados_bancarios', schema='cegep')
    # ### end Alembic commands ###
