"""indisp mtv

Revision ID: 7d718fe198e6
Revises: e724ac5609f6
Create Date: 2025-01-19 09:46:01.347387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d718fe198e6'
down_revision: Union[str, None] = 'e724ac5609f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indisps', sa.Column('mtv', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('indisps', 'mtv')
    # ### end Alembic commands ###
