"""operacao_pessoal: permite mais de um periodo por militar

Revision ID: 7fb64b3ff74e
Revises: a77650626a64
Create Date: 2026-09-14 06:58:10.057871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fb64b3ff74e'
down_revision: Union[str, None] = 'a77650626a64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_operacao_pessoal_user'), 'operacao_pessoal', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_operacao_pessoal_user'), 'operacao_pessoal', ['operacao_id', 'user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
