"""ajustando hash pass

Revision ID: 806d5bf05b8b
Revises: 
Create Date: 2024-09-14 08:24:21.602334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '806d5bf05b8b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('p_g', sa.String(), nullable=False),
    sa.Column('esp', sa.String(), nullable=True),
    sa.Column('nome_guerra', sa.String(), nullable=False),
    sa.Column('nome_completo', sa.String(), nullable=True),
    sa.Column('ult_promo', sa.DateTime(), nullable=True),
    sa.Column('id_fab', sa.Integer(), nullable=True),
    sa.Column('saram', sa.Integer(), nullable=False),
    sa.Column('unidade', sa.String(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=True),
    sa.Column('nasc', sa.DateTime(), nullable=True),
    sa.Column('celular', sa.String(), nullable=True),
    sa.Column('email_pess', sa.String(), nullable=True),
    sa.Column('email_fab', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_fab'),
    sa.UniqueConstraint('saram')
    )
    op.create_table('tripulantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trig', sa.String(length=3), nullable=False),
    sa.Column('func', sa.Enum('mc', 'lm', 'tf', 'os', 'oe', name='funclist'), nullable=False),
    sa.Column('oper', sa.Enum('alno', 'basc', 'oper', 'inst', name='operlist'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trig')
    )
    op.create_table('quad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('nacional', 'local', 'desloc', 'sobr', 'sar', name='quadtype'), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['tripulantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quad')
    op.drop_table('tripulantes')
    op.drop_table('users')
    # ### end Alembic commands ###
