"""index_etapa_id_in_oi_and_trip

Revision ID: 81819113504c
Revises: e32b8c7a4684
Create Date: 2026-05-19 08:51:50.314918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81819113504c'
down_revision: Union[str, None] = 'e32b8c7a4684'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_estatistica_oi_etapa_etapa_id'), 'oi_etapa', ['etapa_id'], unique=False, schema='estatistica')
    op.create_index(op.f('ix_estatistica_trip_etapa_etapa_id'), 'trip_etapa', ['etapa_id'], unique=False, schema='estatistica')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_estatistica_trip_etapa_etapa_id'), table_name='trip_etapa', schema='estatistica')
    op.drop_index(op.f('ix_estatistica_oi_etapa_etapa_id'), table_name='oi_etapa', schema='estatistica')
    # ### end Alembic commands ###
