"""add_updated_at_to_indisp

Revision ID: 85e9285b64c3
Revises: c3cb42ce638d
Create Date: 2025-12-15 10:31:14.041289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85e9285b64c3'
down_revision: Union[str, None] = 'c3cb42ce638d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indisps', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('indisps', 'updated_at')
    # ### end Alembic commands ###
