"""passaporte/visa file_path imagens

Revision ID: 8bf590c41600
Revises: 49ff875dd599
Create Date: 2026-06-26 20:49:15.396014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bf590c41600'
down_revision: Union[str, None] = '49ff875dd599'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('passaportes', sa.Column('passaporte_file_path', sa.String(), nullable=True), schema='inteligencia')
    op.add_column('passaportes', sa.Column('visa_file_path', sa.String(), nullable=True), schema='inteligencia')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('passaportes', 'visa_file_path', schema='inteligencia')
    op.drop_column('passaportes', 'passaporte_file_path', schema='inteligencia')
    # ### end Alembic commands ###
