"""ordem de missao uae and data_Saida

Revision ID: 8dec01d1664d
Revises: 425b0b0c16eb
Create Date: 2026-01-04 10:51:37.158844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dec01d1664d'
down_revision: Union[str, None] = '425b0b0c16eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ordens_missao', sa.Column('uae', sa.String(length=20), nullable=False))
    op.add_column('ordens_missao', sa.Column('data_saida', sa.Date(), nullable=True))
    op.drop_constraint(op.f('ordens_missao_numero_key'), 'ordens_missao', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('ordens_missao_numero_key'), 'ordens_missao', ['numero'], postgresql_nulls_not_distinct=False)
    op.drop_column('ordens_missao', 'data_saida')
    op.drop_column('ordens_missao', 'uae')
    # ### end Alembic commands ###
