"""initial_schema

Revision ID: 8e45a036c6f5
Revises: 
Create Date: 2025-12-30 19:35:11.626565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e45a036c6f5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Criar schemas
    op.execute('CREATE SCHEMA IF NOT EXISTS cegep')
    op.execute('CREATE SCHEMA IF NOT EXISTS security')
    op.execute('CREATE SCHEMA IF NOT EXISTS nav')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etiqueta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cor', sa.String(length=7), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='cegep'
    )
    op.create_table('frag_mis',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('tipo_doc', sa.String(), nullable=False),
    sa.Column('n_doc', sa.Integer(), nullable=False),
    sa.Column('desc', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('afast', sa.DateTime(), nullable=False),
    sa.Column('regres', sa.DateTime(), nullable=False),
    sa.Column('acrec_desloc', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('obs', sa.String(), nullable=True),
    sa.Column('indenizavel', sa.Boolean(), nullable=False),
    sa.Column('custos', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='cegep'
    )
    op.create_table('valor_diarias',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('grupo_pg', sa.Integer(), nullable=False),
    sa.Column('grupo_cid', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='cegep'
    )
    op.create_table('estados',
    sa.Column('codigo_uf', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('uf', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uf')
    )
    op.create_table('posto_grad',
    sa.Column('ant', sa.Integer(), nullable=False),
    sa.Column('short', sa.String(), nullable=False),
    sa.Column('mid', sa.String(), nullable=False),
    sa.Column('long', sa.String(), nullable=False),
    sa.Column('circulo', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('short')
    )
    op.create_table('quads_group',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('short', sa.String(), nullable=False),
    sa.Column('long', sa.String(), nullable=False),
    sa.Column('uae', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oauth2_clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=100), nullable=False),
    sa.Column('client_secret', sa.String(length=255), nullable=True),
    sa.Column('redirect_uri', sa.String(length=255), nullable=False),
    sa.Column('is_confidential', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='security'
    )
    op.create_index(op.f('ix_security_oauth2_clients_client_id'), 'oauth2_clients', ['client_id'], unique=True, schema='security')
    op.create_table('resources',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='security'
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='security'
    )
    op.create_table('frag_etiqueta',
    sa.Column('frag_id', sa.Integer(), nullable=False),
    sa.Column('etiqueta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['etiqueta_id'], ['cegep.etiqueta.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['frag_id'], ['cegep.frag_mis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('frag_id', 'etiqueta_id'),
    schema='cegep'
    )
    op.create_table('grupos_pg',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('grupo', sa.Integer(), nullable=False),
    sa.Column('pg_short', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['pg_short'], ['posto_grad.short'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='cegep'
    )
    op.create_table('cidades',
    sa.Column('codigo', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('uf', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['uf'], ['estados.uf'], ),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('quads_type',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('short', sa.String(), nullable=False),
    sa.Column('long', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['quads_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['security.resources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='security'
    )
    op.create_table('soldos',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('pg', sa.String(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['pg'], ['posto_grad.short'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('p_g', sa.String(), nullable=False),
    sa.Column('esp', sa.String(), nullable=True),
    sa.Column('nome_guerra', sa.String(), nullable=False),
    sa.Column('nome_completo', sa.String(), nullable=True),
    sa.Column('id_fab', sa.Integer(), nullable=True),
    sa.Column('saram', sa.Integer(), nullable=False),
    sa.Column('unidade', sa.String(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=True),
    sa.Column('email_fab', sa.String(), nullable=True),
    sa.Column('email_pess', sa.String(), nullable=True),
    sa.Column('nasc', sa.Date(), nullable=True),
    sa.Column('ult_promo', sa.Date(), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('ant_rel', sa.Integer(), nullable=True),
    sa.Column('first_login', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['p_g'], ['posto_grad.short'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_fab'),
    sa.UniqueConstraint('saram')
    )
    op.create_table('comissionamento',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('dep', sa.Boolean(), nullable=False),
    sa.Column('cache_calc', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('data_ab', sa.Date(), nullable=False),
    sa.Column('qtd_aj_ab', sa.Float(), nullable=False),
    sa.Column('valor_aj_ab', sa.Float(), nullable=False),
    sa.Column('data_fc', sa.Date(), nullable=False),
    sa.Column('qtd_aj_fc', sa.Float(), nullable=False),
    sa.Column('valor_aj_fc', sa.Float(), nullable=False),
    sa.Column('dias_cumprir', sa.Integer(), nullable=True),
    sa.Column('doc_prop', sa.String(), nullable=False),
    sa.Column('doc_aut', sa.String(), nullable=False),
    sa.Column('doc_enc', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='cegep'
    )
    op.create_table('dados_bancarios',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('banco', sa.String(), nullable=False),
    sa.Column('codigo_banco', sa.String(), nullable=False),
    sa.Column('agencia', sa.String(), nullable=False),
    sa.Column('conta', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    schema='cegep'
    )
    op.create_table('grupos_cidade',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('grupo', sa.Integer(), nullable=False),
    sa.Column('cidade_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cidade_id'], ['cidades.codigo'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='cegep'
    )
    op.create_table('pernoite_frag',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('cidade_id', sa.Integer(), nullable=False),
    sa.Column('frag_id', sa.Integer(), nullable=False),
    sa.Column('acrec_desloc', sa.Boolean(), nullable=False),
    sa.Column('data_ini', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('obs', sa.String(), nullable=True),
    sa.Column('meia_diaria', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cidade_id'], ['cidades.codigo'], ),
    sa.ForeignKeyConstraint(['frag_id'], ['cegep.frag_mis.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='cegep'
    )
    op.create_table('users_frag',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('frag_id', sa.Integer(), nullable=False),
    sa.Column('sit', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('p_g', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['frag_id'], ['cegep.frag_mis.id'], ),
    sa.ForeignKeyConstraint(['p_g'], ['posto_grad.short'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='cegep'
    )
    op.create_table('grupos_loc_esp',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('cidade_id', sa.Integer(), nullable=False),
    sa.Column('grupo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cidade_id'], ['cidades.codigo'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('indisps',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_start', sa.Date(), nullable=False),
    sa.Column('date_end', sa.Date(), nullable=False),
    sa.Column('mtv', sa.String(), nullable=False),
    sa.Column('obs', sa.String(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aerodromos',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('codigo_icao', sa.String(), nullable=False),
    sa.Column('codigo_iata', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('elevacao', sa.Float(), nullable=False),
    sa.Column('pais', sa.String(), nullable=False),
    sa.Column('utc', sa.Integer(), nullable=False),
    sa.Column('base_aerea', sa.JSON(), nullable=True),
    sa.Column('codigo_cidade', sa.Integer(), nullable=True),
    sa.Column('cidade_manual', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['codigo_cidade'], ['cidades.codigo'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_icao'),
    schema='nav'
    )
    op.create_table('ordens_missao',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('matricula_anv', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('projeto', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('campos_especiais', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('doc_ref', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('quads_func',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('func', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['quads_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oauth2_authorization_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('code_challenge', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('code_challenge_method', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['security.oauth2_clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='security'
    )
    op.create_index(op.f('ix_security_oauth2_authorization_codes_code'), 'oauth2_authorization_codes', ['code'], unique=True, schema='security')
    op.create_table('oauth2_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(length=255), nullable=False),
    sa.Column('refresh_token', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['security.oauth2_clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='security'
    )
    op.create_index(op.f('ix_security_oauth2_tokens_access_token'), 'oauth2_tokens', ['access_token'], unique=True, schema='security')
    op.create_index(op.f('ix_security_oauth2_tokens_refresh_token'), 'oauth2_tokens', ['refresh_token'], unique=True, schema='security')
    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['security.permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['security.roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='security'
    )
    op.create_table('user_action_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource', sa.String(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('before', sa.String(), nullable=True),
    sa.Column('after', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='security'
    )
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['security.roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='security'
    )
    op.create_table('tripulantes',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trig', sa.String(length=3), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('uae', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('etapas_missao',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('ordem_id', sa.Integer(), nullable=False),
    sa.Column('dt_dep', sa.DateTime(), nullable=False),
    sa.Column('origem', sa.String(length=10), nullable=False),
    sa.Column('dest', sa.String(length=10), nullable=False),
    sa.Column('dt_arr', sa.DateTime(), nullable=False),
    sa.Column('alternativa', sa.String(length=10), nullable=False),
    sa.Column('tvoo_etp', sa.Integer(), nullable=False),
    sa.Column('tvoo_alt', sa.Integer(), nullable=False),
    sa.Column('qtd_comb', sa.Integer(), nullable=False),
    sa.Column('esf_aer', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['ordem_id'], ['ordens_missao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quad',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Date(), nullable=True),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['tripulantes.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['quads_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trip_funcs',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('func', sa.String(), nullable=False),
    sa.Column('oper', sa.String(), nullable=False),
    sa.Column('proj', sa.String(), nullable=False),
    sa.Column('data_op', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['tripulantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tripulacao_ordem',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('ordem_id', sa.Integer(), nullable=False),
    sa.Column('tripulante_id', sa.Integer(), nullable=False),
    sa.Column('funcao', sa.String(length=10), nullable=False),
    sa.Column('p_g', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['ordem_id'], ['ordens_missao.id'], ),
    sa.ForeignKeyConstraint(['p_g'], ['posto_grad.short'], ),
    sa.ForeignKeyConstraint(['tripulante_id'], ['tripulantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tripulacao_ordem')
    op.drop_table('trip_funcs')
    op.drop_table('quad')
    op.drop_table('etapas_missao')
    op.drop_table('tripulantes')
    op.drop_table('user_roles', schema='security')
    op.drop_table('user_action_logs', schema='security')
    op.drop_table('role_permissions', schema='security')
    op.drop_index(op.f('ix_security_oauth2_tokens_refresh_token'), table_name='oauth2_tokens', schema='security')
    op.drop_index(op.f('ix_security_oauth2_tokens_access_token'), table_name='oauth2_tokens', schema='security')
    op.drop_table('oauth2_tokens', schema='security')
    op.drop_index(op.f('ix_security_oauth2_authorization_codes_code'), table_name='oauth2_authorization_codes', schema='security')
    op.drop_table('oauth2_authorization_codes', schema='security')
    op.drop_table('quads_func')
    op.drop_table('ordens_missao')
    op.drop_table('aerodromos', schema='nav')
    op.drop_table('indisps')
    op.drop_table('grupos_loc_esp')
    op.drop_table('users_frag', schema='cegep')
    op.drop_table('pernoite_frag', schema='cegep')
    op.drop_table('grupos_cidade', schema='cegep')
    op.drop_table('dados_bancarios', schema='cegep')
    op.drop_table('comissionamento', schema='cegep')
    op.drop_table('users')
    op.drop_table('soldos')
    op.drop_table('permissions', schema='security')
    op.drop_table('quads_type')
    op.drop_table('cidades')
    op.drop_table('grupos_pg', schema='cegep')
    op.drop_table('frag_etiqueta', schema='cegep')
    op.drop_table('roles', schema='security')
    op.drop_table('resources', schema='security')
    op.drop_index(op.f('ix_security_oauth2_clients_client_id'), table_name='oauth2_clients', schema='security')
    op.drop_table('oauth2_clients', schema='security')
    op.drop_table('quads_group')
    op.drop_table('posto_grad')
    op.drop_table('estados')
    op.drop_table('valor_diarias', schema='cegep')
    op.drop_table('frag_mis', schema='cegep')
    op.drop_table('etiqueta', schema='cegep')
    # Remover schemas
    op.execute('DROP SCHEMA IF EXISTS nav')
    op.execute('DROP SCHEMA IF EXISTS security')
    op.execute('DROP SCHEMA IF EXISTS cegep')
    # ### end Alembic commands ###
