"""custos missao jsonb

Revision ID: 8ef9dcb8bc9a
Revises: 38fd0e053691
Create Date: 2025-11-18 16:24:41.784567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8ef9dcb8bc9a'
down_revision: Union[str, None] = '38fd0e053691'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('frag_mis', sa.Column('custos', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False), schema='cegep')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('frag_mis', 'custos', schema='cegep')
    # ### end Alembic commands ###
