"""add_orcamento_anual

Revision ID: 93742dc1532f
Revises: da4f8ad7e98c
Create Date: 2026-04-25 06:46:42.481188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93742dc1532f'
down_revision: Union[str, None] = 'da4f8ad7e98c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orcamento_anual',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('ano_ref', sa.Integer(), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('abertura', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('fechamento', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.CheckConstraint('abertura + fechamento = total', name='ck_orcamento_anual_soma_cotas'),
    sa.CheckConstraint('abertura >= 0', name='ck_orcamento_anual_abertura_pos'),
    sa.CheckConstraint('fechamento >= 0', name='ck_orcamento_anual_fechamento_pos'),
    sa.CheckConstraint('total >= 0', name='ck_orcamento_anual_total_pos'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ano_ref', name='uq_orcamento_anual_ano_ref'),
    schema='cegep'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orcamento_anual', schema='cegep')
    # ### end Alembic commands ###
