"""add data_op in funcs

Revision ID: 9a6cf88ec6e5
Revises: bf0dab861062
Create Date: 2024-11-30 16:45:43.078586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a6cf88ec6e5'
down_revision: Union[str, None] = 'bf0dab861062'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip_funcs', sa.Column('data_op', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trip_funcs', 'data_op')
    # ### end Alembic commands ###
