"""indisp created_by

Revision ID: a18c8c2f1b2f
Revises: 1e3721fd4a56
Create Date: 2025-02-02 16:18:07.318931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a18c8c2f1b2f'
down_revision: Union[str, None] = '1e3721fd4a56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indisps', sa.Column('created_by', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'indisps', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'indisps', type_='foreignkey')
    op.drop_column('indisps', 'created_by')
    # ### end Alembic commands ###
