"""add custo_cache on comiss

Revision ID: a2a9d3124ce9
Revises: 7b0660382dec
Create Date: 2025-12-17 11:07:29.129747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a2a9d3124ce9'
down_revision: Union[str, None] = '7b0660382dec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comissionamento', sa.Column('cache_calc', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False), schema='cegep')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comissionamento', 'cache_calc', schema='cegep')
    # ### end Alembic commands ###
