"""ajuste valor_diarias

Revision ID: a64df17e1009
Revises: cab0427f6e79
Create Date: 2025-05-14 14:49:29.386820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a64df17e1009'
down_revision: Union[str, None] = 'cab0427f6e79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('valor_diarias_grupo_pg_fkey', 'valor_diarias', schema='cegep', type_='foreignkey')
    op.drop_constraint('valor_diarias_grupo_cid_fkey', 'valor_diarias', schema='cegep', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('valor_diarias_grupo_cid_fkey', 'valor_diarias', 'grupos_cidade', ['grupo_cid'], ['id'], source_schema='cegep', referent_schema='cegep')
    op.create_foreign_key('valor_diarias_grupo_pg_fkey', 'valor_diarias', 'grupos_pg', ['grupo_pg'], ['id'], source_schema='cegep', referent_schema='cegep')
    # ### end Alembic commands ###
