"""rev_financeiro

Revision ID: a756c5e9920e
Revises: cab0427f6e79
Create Date: 2025-07-17 11:04:55.539708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a756c5e9920e'
down_revision: Union[str, None] = 'cab0427f6e79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('frag_mis', sa.Column('tipo_doc', sa.String(), nullable=False), schema='cegep')
    op.add_column('frag_mis', sa.Column('n_doc', sa.Integer(), nullable=False), schema='cegep')
    op.add_column('frag_mis', sa.Column('desc', sa.String(), nullable=False), schema='cegep')
    op.add_column('frag_mis', sa.Column('tipo', sa.String(), nullable=False), schema='cegep')
    op.add_column('frag_mis', sa.Column('afast', sa.DateTime(), nullable=False), schema='cegep')
    op.add_column('frag_mis', sa.Column('regres', sa.DateTime(), nullable=False), schema='cegep')
    op.add_column('frag_mis', sa.Column('indenizavel', sa.Boolean(), nullable=False), schema='cegep')
    op.add_column('pernoite_frag', sa.Column('frag_id', sa.Integer(), nullable=False), schema='cegep')
    op.add_column('pernoite_frag', sa.Column('meia_diaria', sa.Boolean(), nullable=False), schema='cegep')
    op.create_foreign_key("fk_pernoite_frag_frag_id", 'pernoite_frag', 'frag_mis', ['frag_id'], ['id'], source_schema='cegep', referent_schema='cegep')
    op.drop_constraint(op.f('valor_diarias_grupo_pg_fkey'), 'valor_diarias', schema='cegep', type_='foreignkey')
    op.drop_constraint(op.f('valor_diarias_grupo_cid_fkey'), 'valor_diarias', schema='cegep', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('valor_diarias_grupo_cid_fkey'), 'valor_diarias', 'grupos_cidade', ['grupo_cid'], ['id'], source_schema='cegep', referent_schema='cegep')
    op.create_foreign_key(op.f('valor_diarias_grupo_pg_fkey'), 'valor_diarias', 'grupos_pg', ['grupo_pg'], ['id'], source_schema='cegep', referent_schema='cegep')
    op.drop_constraint("fk_pernoite_frag_frag_id", 'pernoite_frag', schema='cegep', type_='foreignkey')
    op.drop_column('pernoite_frag', 'meia_diaria', schema='cegep')
    op.drop_column('pernoite_frag', 'frag_id', schema='cegep')
    op.drop_column('frag_mis', 'indenizavel', schema='cegep')
    op.drop_column('frag_mis', 'regres', schema='cegep')
    op.drop_column('frag_mis', 'afast', schema='cegep')
    op.drop_column('frag_mis', 'tipo', schema='cegep')
    op.drop_column('frag_mis', 'desc', schema='cegep')
    op.drop_column('frag_mis', 'n_doc', schema='cegep')
    op.drop_column('frag_mis', 'tipo_doc', schema='cegep')
    # ### end Alembic commands ###
