"""notificacoes in-app

Revision ID: a77650626a64
Revises: 22778e2241b7
Create Date: 2026-08-29 21:24:44.903893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a77650626a64'
down_revision: Union[str, None] = '22778e2241b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notificacoes',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('uae', sa.String(length=20), nullable=False),
    sa.Column('escopo', sa.String(length=12), nullable=False),
    sa.Column('audiencia', sa.String(length=12), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('titulo', sa.String(length=140), nullable=False),
    sa.Column('recurso', sa.String(length=60), nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=True),
    sa.Column('recurso_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('req_resource', sa.String(length=120), nullable=True),
    sa.Column('req_action', sa.String(length=40), nullable=True),
    sa.Column('chave_dedupe', sa.String(length=120), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(escopo = 'direta' AND user_id IS NOT NULL AND req_resource IS NULL) OR (escopo = 'tarefa' AND user_id IS NULL AND req_resource IS NOT NULL)", name='ck_notificacoes_escopo_enderecamento'),
    sa.CheckConstraint("escopo != 'tarefa' OR audiencia = 'gestor'", name='ck_notificacoes_tarefa_gestor'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uae'], ['organizacoes.sigla'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notificacoes_inbox', 'notificacoes', ['user_id', 'read_at'], unique=False)
    op.create_index('ix_notificacoes_tarefas', 'notificacoes', ['uae', 'escopo', 'resolved_at'], unique=False)
    op.create_index('uq_notificacoes_tarefa_aberta', 'notificacoes', ['uae', 'tipo', 'chave_dedupe'], unique=True, postgresql_where=sa.text("escopo = 'tarefa' AND resolved_at IS NULL"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_notificacoes_tarefa_aberta', table_name='notificacoes', postgresql_where=sa.text("escopo = 'tarefa' AND resolved_at IS NULL"))
    op.drop_index('ix_notificacoes_tarefas', table_name='notificacoes')
    op.drop_index('ix_notificacoes_inbox', table_name='notificacoes')
    op.drop_table('notificacoes')
    # ### end Alembic commands ###
