"""criação tabelas quads_type e quads_group

Revision ID: b52d016531e5
Revises: 121a6b950ed5
Create Date: 2025-01-29 17:37:07.053085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b52d016531e5'
down_revision: Union[str, None] = '121a6b950ed5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quads_group',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('short', sa.String(), nullable=False),
    sa.Column('long', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('quads_type',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('short', sa.String(), nullable=False),
    sa.Column('long', sa.String(), nullable=False),
    sa.Column('exclude', sa.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['quads_group.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quads_type')
    op.drop_table('quads_group')
    # ### end Alembic commands ###
