"""unique role_permissions (role, permission)

Revision ID: bbf8cfa798c7
Revises: f8acd17e8ad0
Create Date: 2026-08-18 10:10:04.797008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbf8cfa798c7'
down_revision: Union[str, None] = 'f8acd17e8ad0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # A tabela ja carrega duplicatas (ex.: apoio_avancado x comiss.view), e a
    # constraint nao entra sem limpa-las antes. Fica a linha de menor id de
    # cada par: e a original; as demais nunca significaram nada.
    op.execute("""
        DELETE FROM security.role_permissions a
        USING security.role_permissions b
        WHERE a.role_id = b.role_id
          AND a.permission_id = b.permission_id
          AND a.id > b.id
    """)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_role_permissions_role_perm', 'role_permissions', ['role_id', 'permission_id'], schema='security')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_role_permissions_role_perm', 'role_permissions', schema='security', type_='unique')
    # ### end Alembic commands ###
