"""criação tabela funcoes

Revision ID: bf0dab861062
Revises: a109722a7130
Create Date: 2024-09-22 10:26:39.973516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf0dab861062'
down_revision: Union[str, None] = 'a109722a7130'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('nacional', 'local', 'desloc', 'sobr', 'sar', name='quadtype'), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['tripulantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trip_funcs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('func', sa.String(), nullable=False),
    sa.Column('oper', sa.String(), nullable=False),
    sa.Column('proj', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['tripulantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trip_funcs')
    op.drop_table('quad')
    # ### end Alembic commands ###
