"""feedback eventos conversa

Revision ID: c283bebf8219
Revises: ca0f7b1a695d
Create Date: 2026-09-26 13:08:58.220151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c283bebf8219'
down_revision: Union[str, None] = 'ca0f7b1a695d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback_eventos',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('feedback_id', sa.Integer(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('texto', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(tipo = 'mensagem' AND texto IS NOT NULL AND status IS NULL) OR (tipo = 'status' AND status IS NOT NULL AND texto IS NULL)", name='ck_feedback_eventos_tipo_conteudo'),
    sa.ForeignKeyConstraint(['autor_id'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedbacks.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feedback_eventos_feedback', 'feedback_eventos', ['feedback_id', 'created_at'], unique=False)
    op.add_column('feedbacks', sa.Column('origem', sa.String(length=20), server_default='fatbird', nullable=False))
    # Cópia de dado (o autogenerate não sabe fazer): cada resposta única
    # vira a primeira mensagem da administração na conversa. Exceção
    # justificada à regra de não editar migration gerada.
    op.execute(
        """
        INSERT INTO feedback_eventos
            (feedback_id, autor_id, tipo, texto, created_at)
        SELECT id, respondido_por, 'mensagem', resposta,
               COALESCE(respondido_em, updated_at, created_at)
        FROM feedbacks
        WHERE resposta IS NOT NULL
        """
    )
    op.drop_constraint(op.f('feedbacks_respondido_por_fkey'), 'feedbacks', type_='foreignkey')
    op.drop_column('feedbacks', 'respondido_em')
    op.drop_column('feedbacks', 'resposta')
    op.drop_column('feedbacks', 'respondido_por')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedbacks', sa.Column('respondido_por', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('feedbacks', sa.Column('resposta', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('feedbacks', sa.Column('respondido_em', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('feedbacks_respondido_por_fkey'), 'feedbacks', 'users', ['respondido_por'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    # Volta a ÚLTIMA mensagem da administração para a resposta única; o
    # resto da conversa se perde (aceito na spec).
    op.execute(
        """
        UPDATE feedbacks f
        SET resposta = e.texto,
            respondido_por = e.autor_id,
            respondido_em = e.created_at
        FROM (
            SELECT DISTINCT ON (ev.feedback_id)
                ev.feedback_id, ev.texto, ev.autor_id, ev.created_at
            FROM feedback_eventos ev
            JOIN feedbacks fb ON fb.id = ev.feedback_id
            WHERE ev.tipo = 'mensagem'
              AND ev.autor_id IS DISTINCT FROM fb.user_id
            ORDER BY ev.feedback_id, ev.created_at DESC, ev.id DESC
        ) e
        WHERE f.id = e.feedback_id
        """
    )
    op.drop_column('feedbacks', 'origem')
    op.drop_index('ix_feedback_eventos_feedback', table_name='feedback_eventos')
    op.drop_table('feedback_eventos')
    # ### end Alembic commands ###
