"""add nav schema and aerodromos table

Revision ID: c3cb42ce638d
Revises: 7c95b11b6c7b
Create Date: 2025-12-01 21:04:15.642976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3cb42ce638d'
down_revision: Union[str, None] = '7c95b11b6c7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Criar schema nav
    op.execute('CREATE SCHEMA IF NOT EXISTS nav')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aerodromos',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('codigo_icao', sa.String(), nullable=False),
    sa.Column('codigo_iata', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('elevacao', sa.Float(), nullable=False),
    sa.Column('pais', sa.String(), nullable=False),
    sa.Column('utc', sa.Integer(), nullable=False),
    sa.Column('base_aerea', sa.JSON(), nullable=True),
    sa.Column('codigo_cidade', sa.Integer(), nullable=True),
    sa.Column('cidade_manual', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['codigo_cidade'], ['cidades.codigo'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_icao'),
    schema='nav'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aerodromos', schema='nav')
    # ### end Alembic commands ###

    # Remover schema nav
    op.execute('DROP SCHEMA IF EXISTS nav CASCADE')
