"""relatorios_voo

Revision ID: ca0f7b1a695d
Revises: e325fdc5090b
Create Date: 2026-09-23 16:34:50.016186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca0f7b1a695d'
down_revision: Union[str, None] = 'e325fdc5090b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relatorios_voo',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('uae', sa.String(length=20), nullable=False),
    sa.Column('anv', sa.String(length=4), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('seq', sa.SmallInteger(), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('num_paginas', sa.SmallInteger(), nullable=True),
    sa.Column('obs', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['anv'], ['aeronaves.matricula'], ),
    sa.ForeignKeyConstraint(['uae'], ['tenants.organizacao_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uae', 'anv', 'data', 'seq', name='uq_relatorios_voo_dia_seq'),
    sa.UniqueConstraint('uae', 'sha256', name='uq_relatorios_voo_sha256'),
    schema='estatistica'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relatorios_voo', schema='estatistica')
    # ### end Alembic commands ###
