"""ordens de missão

Revision ID: ca7ac9e9e2e6
Revises: 349bc7a3af18
Create Date: 2025-12-28 19:33:20.684521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca7ac9e9e2e6'
down_revision: Union[str, None] = '349bc7a3af18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ordens_missao',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('matricula_anv', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('projeto', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('campos_especiais', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('doc_ref', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('etapas_missao',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('ordem_id', sa.Integer(), nullable=False),
    sa.Column('dt_dep', sa.DateTime(), nullable=False),
    sa.Column('origem', sa.String(length=10), nullable=False),
    sa.Column('dest', sa.String(length=10), nullable=False),
    sa.Column('dt_arr', sa.DateTime(), nullable=False),
    sa.Column('alternativa', sa.String(length=10), nullable=False),
    sa.Column('tvoo_etp', sa.Integer(), nullable=False),
    sa.Column('tvoo_alt', sa.Integer(), nullable=False),
    sa.Column('qtd_comb', sa.Integer(), nullable=False),
    sa.Column('esf_aer', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['ordem_id'], ['ordens_missao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tripulacao_ordem',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('ordem_id', sa.Integer(), nullable=False),
    sa.Column('tripulante_id', sa.Integer(), nullable=False),
    sa.Column('funcao', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['ordem_id'], ['ordens_missao.id'], ),
    sa.ForeignKeyConstraint(['tripulante_id'], ['tripulantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tripulacao_ordem')
    op.drop_table('etapas_missao')
    op.drop_table('ordens_missao')
    # ### end Alembic commands ###
