"""implementando fragmento de missoes em cegep

Revision ID: cab0427f6e79
Revises: 1aa666b664a7
Create Date: 2025-05-13 19:59:59.475659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cab0427f6e79'
down_revision: Union[str, None] = '1aa666b664a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('frag_mis',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('obs', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='cegep'
    )
    op.create_table('pernoite_frag',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('cidade_id', sa.Integer(), nullable=False),
    sa.Column('acrec_desloc', sa.Boolean(), nullable=False),
    sa.Column('data_ini', sa.DateTime(), nullable=True),
    sa.Column('data_fim', sa.DateTime(), nullable=True),
    sa.Column('obs', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cidade_id'], ['cidades.codigo'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='cegep'
    )
    op.create_table('users_frag',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('frag_id', sa.Integer(), nullable=False),
    sa.Column('sit', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('p_g', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['frag_id'], ['cegep.frag_mis.id'], ),
    sa.ForeignKeyConstraint(['p_g'], ['posto_grad.short'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='cegep'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_frag', schema='cegep')
    op.drop_table('pernoite_frag', schema='cegep')
    op.drop_table('frag_mis', schema='cegep')
    # ### end Alembic commands ###
