"""add inteligencia schema and passaportes table

Revision ID: cd008c17ffd9
Revises: f862abe68946
Create Date: 2026-03-21 08:12:10.957197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd008c17ffd9'
down_revision: Union[str, None] = 'f862abe68946'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute('CREATE SCHEMA IF NOT EXISTS inteligencia')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passaportes',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('passaporte', sa.String(length=20), nullable=True),
    sa.Column('validade_passaporte', sa.Date(), nullable=True),
    sa.Column('validade_visa', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    schema='inteligencia'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('passaportes', schema='inteligencia')
    op.execute('DROP SCHEMA IF EXISTS inteligencia')
    # ### end Alembic commands ###
