"""add is_simulador to missao

Revision ID: da4f8ad7e98c
Revises: 65c2476a7f97
Create Date: 2026-03-31 18:11:36.862446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da4f8ad7e98c'
down_revision: Union[str, None] = '65c2476a7f97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('missao', sa.Column('is_simulador', sa.Boolean(), server_default='false', nullable=False), schema='estatistica')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('missao', 'is_simulador', schema='estatistica')
    # ### end Alembic commands ###
