"""add saudacao to tenants

Revision ID: deec47cf5bb0
Revises: 018236c03384
Create Date: 2026-07-11 21:12:11.386733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'deec47cf5bb0'
down_revision: Union[str, None] = '018236c03384'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('saudacao', sa.String(length=120), server_default=sa.text("''"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'saudacao')
    # ### end Alembic commands ###
