"""gle: localidades especiais e missoes de apuracao

Revision ID: e325fdc5090b
Revises: 7fb64b3ff74e
Create Date: 2026-09-18 12:31:16.686870

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e325fdc5090b'
down_revision: Union[str, None] = '7fb64b3ff74e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'missao_gle',
        sa.Column(
            'id', sa.Integer(), sa.Identity(always=False), nullable=False
        ),
        sa.Column('descricao', sa.String(), nullable=False),
        sa.Column('obs', sa.String(), nullable=True),
        sa.Column('uae', sa.String(length=20), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['uae'],
            ['tenants.organizacao_id'],
            onupdate='CASCADE',
            ondelete='RESTRICT',
        ),
        sa.PrimaryKeyConstraint('id'),
        schema='cegep',
    )
    op.create_table(
        'militar_gle',
        sa.Column(
            'id', sa.Integer(), sa.Identity(always=False), nullable=False
        ),
        sa.Column('missao_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('p_g', sa.String(length=2), nullable=False),
        sa.ForeignKeyConstraint(
            ['missao_id'], ['cegep.missao_gle.id'], ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['p_g'],
            ['posto_grad.short'],
        ),
        sa.ForeignKeyConstraint(
            ['user_id'], ['users.id'], ondelete='RESTRICT'
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'missao_id', 'user_id', name='uq_militar_gle_missao_user'
        ),
        schema='cegep',
    )
    op.create_table(
        'trecho_gle',
        sa.Column(
            'id', sa.Integer(), sa.Identity(always=False), nullable=False
        ),
        sa.Column('missao_id', sa.Integer(), nullable=False),
        sa.Column('loc_esp_id', sa.Integer(), nullable=False),
        sa.Column('chegada', sa.DateTime(), nullable=False),
        sa.Column('afastamento', sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            'afastamento > chegada', name='ck_trecho_gle_periodo'
        ),
        sa.ForeignKeyConstraint(
            ['loc_esp_id'], ['grupos_loc_esp.id'], ondelete='RESTRICT'
        ),
        sa.ForeignKeyConstraint(
            ['missao_id'], ['cegep.missao_gle.id'], ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id'),
        schema='cegep',
    )
    op.create_table(
        'loc_esp_icao',
        sa.Column(
            'id', sa.Integer(), sa.Identity(always=False), nullable=False
        ),
        sa.Column('loc_esp_id', sa.Integer(), nullable=False),
        sa.Column('icao', sa.String(length=4), nullable=False),
        sa.CheckConstraint(
            "icao ~ '^[A-Z]{4}$'", name='ck_loc_esp_icao_formato'
        ),
        sa.ForeignKeyConstraint(
            ['loc_esp_id'], ['grupos_loc_esp.id'], ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('icao', name='uq_loc_esp_icao'),
    )
    # `server_default` temporario: a tabela ja tem linhas em DEV e em
    # producao, e `NOT NULL` sem default quebraria o ALTER. -3 (Brasilia)
    # cobre a maioria; o valor certo de cada localidade e ajustado na tela.
    # O default sai em seguida para que novas linhas informem o fuso.
    op.add_column(
        'grupos_loc_esp',
        sa.Column('fuso', sa.Integer(), nullable=False, server_default='-3'),
    )
    op.alter_column('grupos_loc_esp', 'fuso', server_default=None)
    op.create_unique_constraint(
        'uq_grupos_loc_esp_cidade', 'grupos_loc_esp', ['cidade_id']
    )
    # ### end Alembic commands ###

    # O autogenerate nao compara CheckConstraint de tabela ja existente:
    # estes descrevem o model e por isso vao a mao. O de `fuso` depende da
    # coluna criada acima.
    op.create_check_constraint(
        'ck_grupos_loc_esp_grupo', 'grupos_loc_esp', 'grupo IN (1, 2)'
    )
    op.create_check_constraint(
        'ck_grupos_loc_esp_fuso', 'grupos_loc_esp', 'fuso BETWEEN -5 AND 0'
    )


def downgrade() -> None:
    op.drop_constraint(
        'ck_grupos_loc_esp_fuso', 'grupos_loc_esp', type_='check'
    )
    op.drop_constraint(
        'ck_grupos_loc_esp_grupo', 'grupos_loc_esp', type_='check'
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'uq_grupos_loc_esp_cidade', 'grupos_loc_esp', type_='unique'
    )
    op.drop_column('grupos_loc_esp', 'fuso')
    op.drop_table('loc_esp_icao')
    op.drop_table('trecho_gle', schema='cegep')
    op.drop_table('militar_gle', schema='cegep')
    op.drop_table('missao_gle', schema='cegep')
    # ### end Alembic commands ###
