"""inserindo first_login user

Revision ID: e48d203a2a63
Revises: 5860a920441a
Create Date: 2025-02-24 11:41:53.157510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e48d203a2a63'
down_revision: Union[str, None] = '5860a920441a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'quads_func', ['id'])
    op.add_column('users', sa.Column('first_login', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'first_login')
    op.drop_constraint(None, 'quads_func', type_='unique')
    # ### end Alembic commands ###
