"""remove cadastro de aerodromos

Revision ID: e53393fa2afc
Revises: 605c751aabf4
Create Date: 2026-08-27 10:28:05.263859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e53393fa2afc'
down_revision: Union[str, None] = '605c751aabf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aerodromos', schema='nav')
    # ### end Alembic commands ###
    # aerodromos era a unica tabela do schema nav
    op.execute('DROP SCHEMA IF EXISTS nav')


def downgrade() -> None:
    op.execute('CREATE SCHEMA IF NOT EXISTS nav')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aerodromos',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('codigo_icao', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('codigo_iata', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('elevacao', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('pais', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('utc', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('base_aerea', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('codigo_cidade', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cidade_manual', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['codigo_cidade'], ['cidades.codigo'], name=op.f('aerodromos_codigo_cidade_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('aerodromos_pkey')),
    sa.UniqueConstraint('codigo_icao', name=op.f('aerodromos_codigo_icao_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='nav'
    )
    # ### end Alembic commands ###
