"""comissionamento

Revision ID: e6bd9eadaa0f
Revises: 2765b696ed0f
Create Date: 2025-07-29 09:09:09.150124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6bd9eadaa0f'
down_revision: Union[str, None] = '2765b696ed0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comissionamento',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('dep', sa.Boolean(), nullable=False),
    sa.Column('data_ab', sa.Date(), nullable=False),
    sa.Column('qtd_aj_ab', sa.Float(), nullable=False),
    sa.Column('valor_aj_ab', sa.Float(), nullable=False),
    sa.Column('data_fc', sa.Date(), nullable=False),
    sa.Column('qtd_aj_fc', sa.Float(), nullable=False),
    sa.Column('valor_aj_fc', sa.Float(), nullable=False),
    sa.Column('dias_cumprir', sa.Integer(), nullable=True),
    sa.Column('doc_prop', sa.String(), nullable=False),
    sa.Column('doc_aut', sa.String(), nullable=False),
    sa.Column('doc_enc', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='cegep'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comissionamento', schema='cegep')
    # ### end Alembic commands ###
