"""descrição e tipo em fragmento de ordem

Revision ID: f1f38e6d1891
Revises: a64df17e1009
Create Date: 2025-05-15 11:33:25.722804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1f38e6d1891'
down_revision: Union[str, None] = 'a64df17e1009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('frag_mis', sa.Column('desc', sa.String(), nullable=False), schema='cegep')
    op.add_column('frag_mis', sa.Column('tipo', sa.String(), nullable=False), schema='cegep')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('frag_mis', 'tipo', schema='cegep')
    op.drop_column('frag_mis', 'desc', schema='cegep')
    # ### end Alembic commands ###
