"""add quadro to users and promo_users table

Revision ID: f35acf67d86e
Revises: be1244173be7
Create Date: 2026-06-05 08:49:17.097689

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f35acf67d86e'
down_revision: Union[str, None] = 'be1244173be7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'promo_users',
        sa.Column(
            'id', sa.Integer(), sa.Identity(always=False), nullable=False
        ),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('p_g', sa.String(length=2), nullable=False),
        sa.Column('data_promo', sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ['p_g'],
            ['posto_grad.short'],
        ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'user_id', 'data_promo', name='uq_promo_users_user_data'
        ),
        sa.UniqueConstraint('user_id', 'p_g', name='uq_promo_users_user_pg'),
    )
    op.add_column('users', sa.Column('quadro', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'quadro')
    op.drop_table('promo_users')
    # ### end Alembic commands ###
