"""excluindo celular

Revision ID: f585e6485d5e
Revises: 806d5bf05b8b
Create Date: 2024-09-14 08:44:11.037848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f585e6485d5e'
down_revision: Union[str, None] = '806d5bf05b8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'celular')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('celular', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
