"""change user table optimize

Revision ID: f65f02804ad6
Revises: 029a74e6f1b3
Create Date: 2026-01-22 09:58:10.233210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f65f02804ad6'
down_revision: Union[str, None] = '029a74e6f1b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'p_g',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=2),
               existing_nullable=False)
    op.alter_column('users', 'id_fab',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=6),
               existing_nullable=True,
               postgresql_using='id_fab::text')
    op.alter_column('users', 'saram',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=7),
               existing_nullable=False,
               postgresql_using='saram::text')
    op.alter_column('users', 'cpf',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=11),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'cpf',
               existing_type=sa.String(length=11),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('users', 'saram',
               existing_type=sa.String(length=7),
               type_=sa.INTEGER(),
               existing_nullable=False,
               postgresql_using='saram::integer')
    op.alter_column('users', 'id_fab',
               existing_type=sa.String(length=6),
               type_=sa.INTEGER(),
               existing_nullable=True,
               postgresql_using='id_fab::integer')
    op.alter_column('users', 'p_g',
               existing_type=sa.String(length=2),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
