"""add especificos etapa pqd revo heavy_cds

Revision ID: f75b32a52903
Revises: 81819113504c
Create Date: 2026-05-21 07:40:05.467439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f75b32a52903'
down_revision: Union[str, None] = '81819113504c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('heavy_cds_etapa',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('etapa_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=5), nullable=False),
    sa.Column('peso', sa.SmallInteger(), nullable=False),
    sa.Column('dist', sa.SmallInteger(), nullable=False),
    sa.Column('radial', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint("tipo IN ('heavy', 'cds')", name='ck_heavy_cds_tipo'),
    sa.CheckConstraint('dist >= 0', name='ck_heavy_cds_dist_nn'),
    sa.CheckConstraint('peso >= 0', name='ck_heavy_cds_peso_nn'),
    sa.CheckConstraint('radial >= 0 AND radial < 360', name='ck_heavy_cds_radial_range'),
    sa.ForeignKeyConstraint(['etapa_id'], ['estatistica.etapas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='estatistica'
    )
    op.create_index(op.f('ix_estatistica_heavy_cds_etapa_etapa_id'), 'heavy_cds_etapa', ['etapa_id'], unique=False, schema='estatistica')
    op.create_table('pqd_etapa',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('etapa_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=5), nullable=False),
    sa.Column('qtd', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint("tipo IN ('VTC', 'LV', 'PREC', 'LIVRE')", name='ck_pqd_tipo'),
    sa.CheckConstraint('qtd >= 0', name='ck_pqd_qtd_nn'),
    sa.ForeignKeyConstraint(['etapa_id'], ['estatistica.etapas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='estatistica'
    )
    op.create_index(op.f('ix_estatistica_pqd_etapa_etapa_id'), 'pqd_etapa', ['etapa_id'], unique=False, schema='estatistica')
    op.create_table('revo_etapa',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('etapa_id', sa.Integer(), nullable=False),
    sa.Column('comb_transf', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint('comb_transf >= 0', name='ck_revo_comb_transf_nn'),
    sa.ForeignKeyConstraint(['etapa_id'], ['estatistica.etapas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='estatistica'
    )
    op.create_index(op.f('ix_estatistica_revo_etapa_etapa_id'), 'revo_etapa', ['etapa_id'], unique=False, schema='estatistica')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_estatistica_revo_etapa_etapa_id'), table_name='revo_etapa', schema='estatistica')
    op.drop_table('revo_etapa', schema='estatistica')
    op.drop_index(op.f('ix_estatistica_pqd_etapa_etapa_id'), table_name='pqd_etapa', schema='estatistica')
    op.drop_table('pqd_etapa', schema='estatistica')
    op.drop_index(op.f('ix_estatistica_heavy_cds_etapa_etapa_id'), table_name='heavy_cds_etapa', schema='estatistica')
    op.drop_table('heavy_cds_etapa', schema='estatistica')
    # ### end Alembic commands ###
