"""add instrucao schema and idiomas_habilidades table

Revision ID: f862abe68946
Revises: 11b4c104620e
Create Date: 2026-03-20 19:40:09.813121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f862abe68946'
down_revision: Union[str, None] = '11b4c104620e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute('CREATE SCHEMA IF NOT EXISTS instrucao')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idiomas_habilidades',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ptai_validade', sa.Date(), nullable=True),
    sa.Column('tai_s_validade', sa.Date(), nullable=True),
    sa.Column('tai_s1_validade', sa.Date(), nullable=True),
    sa.Column('hab_espanhol', sa.String(length=2), nullable=True),
    sa.Column('val_espanhol', sa.Date(), nullable=True),
    sa.Column('hab_ingles', sa.String(length=2), nullable=True),
    sa.Column('val_ingles', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    schema='instrucao'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('idiomas_habilidades', schema='instrucao')
    op.execute('DROP SCHEMA IF EXISTS instrucao')
    # ### end Alembic commands ###
