"""propostas de comissionamento (cenarios e linhas)

Revision ID: f8acd17e8ad0
Revises: 4977ff3a42f0
Create Date: 2026-08-16 14:58:21.420167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8acd17e8ad0'
down_revision: Union[str, None] = '4977ff3a42f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('propostas',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('uae', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('ano_ref', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='rascunho', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ano_ref >= 2026 AND ano_ref <= 2100', name='ck_propostas_ano_ref_plausivel'),
    sa.ForeignKeyConstraint(['uae'], ['tenants.organizacao_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='cegep'
    )
    op.create_table('cenarios',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('proposta_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('cor', sa.String(length=20), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['proposta_id'], ['cegep.propostas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proposta_id', 'ordem', name='uq_cenarios_proposta_ordem', deferrable=True, initially='DEFERRED'),
    schema='cegep'
    )
    op.create_table('cenario_linhas',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('cenario_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('base_ab', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('qtd_ab', sa.Float(), nullable=False),
    sa.Column('ano_ab', sa.Integer(), nullable=False),
    sa.Column('base_fc', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('qtd_fc', sa.Float(), nullable=False),
    sa.Column('ano_fc', sa.Integer(), nullable=False),
    sa.CheckConstraint('ano_fc >= ano_ab', name='ck_cenario_linhas_ordem_exercicios'),
    sa.CheckConstraint('base_ab >= 0 AND base_fc >= 0', name='ck_cenario_linhas_base_nao_negativa'),
    sa.CheckConstraint('qtd_ab > 0 AND qtd_ab <= 2 AND qtd_fc > 0 AND qtd_fc <= 2', name='ck_cenario_linhas_qtd_ajuda'),
    sa.ForeignKeyConstraint(['cenario_id'], ['cegep.cenarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cenario_id', 'user_id', name='uq_cenario_linhas_cenario_user', deferrable=True, initially='DEFERRED'),
    schema='cegep'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cenario_linhas', schema='cegep')
    op.drop_table('cenarios', schema='cegep')
    op.drop_table('propostas', schema='cegep')
    # ### end Alembic commands ###
