"""ajuste quads

Revision ID: f9e861c289f3
Revises:
Create Date: 2024-12-28 14:43:06.737609

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f9e861c289f3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column('p_g', sa.String(), nullable=False),
        sa.Column('esp', sa.String(), nullable=True),
        sa.Column('nome_guerra', sa.String(), nullable=False),
        sa.Column('nome_completo', sa.String(), nullable=True),
        sa.Column('id_fab', sa.Integer(), nullable=True),
        sa.Column('saram', sa.Integer(), nullable=False),
        sa.Column('unidade', sa.String(), nullable=False),
        sa.Column('cpf', sa.String(), nullable=True),
        sa.Column('email_fab', sa.String(), nullable=True),
        sa.Column('email_pess', sa.String(), nullable=True),
        sa.Column('nasc', sa.Date(), nullable=True),
        sa.Column('ult_promo', sa.Date(), nullable=True),
        sa.Column('password', sa.String(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id_fab'),
        sa.UniqueConstraint('saram'),
    )
    op.create_table(
        'tripulantes',
        sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('trig', sa.String(length=3), nullable=False),
        sa.Column('active', sa.Boolean(), nullable=False),
        sa.Column('uae', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'quad',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('description', sa.String(), nullable=False),
        sa.Column('type', sa.String(), nullable=False),
        sa.Column('value', sa.Date(), nullable=True),
        sa.Column('trip_id', sa.Integer(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['trip_id'],
            ['tripulantes.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'trip_funcs',
        sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column('trip_id', sa.Integer(), nullable=False),
        sa.Column('func', sa.String(), nullable=False),
        sa.Column('oper', sa.String(), nullable=False),
        sa.Column('proj', sa.String(), nullable=False),
        sa.Column('data_op', sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ['trip_id'],
            ['tripulantes.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trip_funcs')
    op.drop_table('quad')
    op.drop_table('tripulantes')
    op.drop_table('users')
    # ### end Alembic commands ###
