"""aeronave_table_and_om_matricula_str_fk

Revision ID: fad4c748fc3e
Revises: f65f02804ad6
Create Date: 2026-02-15 10:01:13.224542

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fad4c748fc3e'
down_revision: Union[str, None] = 'f65f02804ad6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aeronaves',
    sa.Column('matricula', sa.String(length=4), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('sit', sa.String(length=2), nullable=False),
    sa.Column('obs', sa.String(), nullable=True),
    sa.Column('prox_insp', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('matricula')
    )
    op.alter_column(
        'om_ordens_missao',
        'matricula_anv',
        existing_type=sa.INTEGER(),
        type_=sa.String(length=4),
        existing_nullable=False,
        postgresql_using='matricula_anv::varchar(4)',
    )

    # Seed aeronaves orfas que ja existem em om_ordens_missao
    conn = op.get_bind()
    conn.execute(sa.text(
        "INSERT INTO aeronaves (matricula, active, sit)"
        " SELECT DISTINCT matricula_anv::varchar(4), true, 'DI'"
        " FROM om_ordens_missao"
        " WHERE matricula_anv::varchar(4) NOT IN"
        " (SELECT matricula FROM aeronaves)"
    ))

    op.create_foreign_key(
        'fk_om_matricula_anv',
        'om_ordens_missao',
        'aeronaves',
        ['matricula_anv'],
        ['matricula'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fk_om_matricula_anv',
        'om_ordens_missao',
        type_='foreignkey',
    )
    op.alter_column(
        'om_ordens_missao',
        'matricula_anv',
        existing_type=sa.String(length=4),
        type_=sa.INTEGER(),
        existing_nullable=False,
        postgresql_using='matricula_anv::integer',
    )
    op.drop_table('aeronaves')
    # ### end Alembic commands ###
